### PR TITLE
rpi-base: Added missing HiFiBerry

### PR DESCRIPTION
**Pull request by kluszon**
**- What I did**

Added missing support for HiFiBerry AMP100, AMP3, AMP4 Pro, DAC+ ADC Pro, DAC+ DSP, DAC+ HD, Digi Pro.

**- How I did it**

Add right lines to rpi-base.inc. Changes were tested and works fine with the branch.

Connected also with issue #1168

### CODE REVIEW

**Comment by kluszon** [comment]
@agherzan What is wrong with DCO? The commit message has required formatting.

**Comment by kraj** [comment]
> @agherzan What is wrong with DCO? The commit message has required formatting.

DCO - Developer Certificate of Origin, basically you add Signed-off-by: tag to indicate that the work came from you.

**Comment by kluszon** [comment]
> DCO - Developer Certificate of Origin, basically you add Signed-off-by: tag to indicate that the work came from you.

I know that. Strange because the commit had "Signed-off-by" section. I did rebase, removed it and added it again.

**Comment by agherzan** [comment]
It's an edge case on the CI side. It falls apart when the incoming branch is the same as the destination branch (in name). "master" and "master" in this case. Don't worry about it.

**Comment by agherzan** [comment]
@kluszon Can you please cleanup the merge commits?

**Comment by kluszon** [comment]
@agherzan I removed any other changes. Please merge it.

**Review by agherzan — APPROVED** [review]
Thanks! This looks great!

**Pull request merged**
