### PR TITLE
gstreamer: Adjust for meson conversion

### PR DESCRIPTION
**Pull request by shr-project**
Depends on https://github.com/agherzan/meta-raspberrypi/pull/565 and http://lists.openembedded.org/pipermail/openembedded-core/2020-January/291811.html and http://lists.openembedded.org/pipermail/openembedded-core/2020-January/291812.html which are now in master-next.

### CODE REVIEW

**Comment by agherzan** [comment]
It still fails on python3 stuff. Hopefully, that gets in soon also.

**Comment by shr-project** [comment]
> It still fails on python3 stuff. Hopefully, that gets in soon also.

Last python3 parsing issue is probably fixed in: https://github.com/agherzan/meta-raspberrypi/pull/566

**Comment by kraj** [comment]
https://github.com/agherzan/meta-raspberrypi/pull/572 should fix it fully but there are other issues as reported in https://github.com/agherzan/meta-raspberrypi/pull/572

**Comment by shr-project** [comment]
Included commit from https://github.com/agherzan/meta-raspberrypi/pull/564 and https://github.com/agherzan/meta-raspberrypi/pull/572 to resolve python3 issue and make CI happy.

**Comment by agherzan** [comment]
Nice. Thanks @shr-project

**Pull request merged**
