### PR TITLE
linux-raspberrypi_6.6 : update kernel and fix DSI display

### LINKED ISSUE #1371: Raspberry Pi 7inch Display + KMS are displaying black/white bars
**Description**
The official Raspberry Pi 7 inch display consistently displays black and white bars after boot when using the KMS graphics driver. The HDMI display does show the correct output however. Pictures attached.

**Steps to reproduce the issue:**
`
MACHINE = "raspberrypi4"
DISTRO = "poky"
EXTRA_IMAGE_FEATURES = "debug-tweaks"
ENABLE_UART = "1"
IMAGE_INSTALL:append = " kmscube"
LICENSE_FLAGS_ACCEPTED += "synaptics-killswitch"
`

`
bitbake core-image-base
`

**Describe the results you received:**
The RPi 7in display does initially show the rainbow screen and four raspberry graphics, but then immediately fades out to black and white bars. The HDMI display shows the rainbow and raspberry graphics like the RPi display but boots to a visible console and can launch kmscube successfully.

**Describe the results you expected:**
console and kmscube working on the RPi 7in display.

**Additional information you deem important (e.g. issue happens only occasionally):**
Attempted using RPi OS - does work correctly!
Attempted using FKMS driver - does display correctly on 7inch display but does *not* respond to touch input.
Attempted using 32bit vs 64bit - no effect.
Attempted using Linux kernel 6.1 - no effect.
Attempted replacing touchscreen, Pi, cable, reseating everything - no effect.

**Additional details (revisions used, host distro, etc.):**
poky - scarthgap - latest
meta-raspberrypi - scarthgap - latest

Let me know if I can provide any logs or can attempt any other debugging steps because I'm running out of ideas.

PXL_20240924_163337655 MP
PXL_20240924_152128629 MP

### PR DESCRIPTION
**Pull request by perezmeyer**
This update seems to fix #1371

Closes: #1371

**- What I did**

**- How I did it**

### CODE REVIEW

**Review by kraj — APPROVED** [review]
LGTM

**Comment by perezmeyer** [comment]
@kraj I pushed a fix for DCO and also rebased against current scarthgap. Will you need another PR for master?

**Comment by kraj** [comment]
> @kraj I pushed a fix for DCO and also rebased against current scarthgap. Will you need another PR for master?

we actually need for `master` first once applied then backported to `scarthgap`

**Comment by moto-timo** [comment]
I already submitted a 6.6.51 upgrade in https://github.com/agherzan/meta-raspberrypi/pull/1374

**Comment by perezmeyer** [comment]
`SRCREV_machine` is in a different value, so I guess I'll have to double check if the fix for #1371 is applied there.

**Comment by perezmeyer** [comment]
Dropping in favor of https://github.com/agherzan/meta-raspberrypi/pull/1377

**Pull request closed without merging**
