### PR TITLE
raspberrypi3-64 shouldn't inherit raspberrypi.

### PR DESCRIPTION
**Pull request by michal-mazurek**
This causes problems and raspberrypi3 does not do that.

connect https://github.com/agherzan/meta-raspberrypi/issues/85

### CODE REVIEW

**Comment by floion** [comment]
merge it :+1:  :)

**Comment by agherzan** [comment]
add to whitelist

**Comment by agherzan** [comment]
test this please

**Comment by agherzan** [comment]
CC @kraj

**Comment by floion** [comment]
can this also go to the morty branch @agherzan ?

**Comment by agherzan** [comment]
Yes we can. @michal-mazurek , can you push a PR with this change above morty too?

**Pull request merged**
