### PR TITLE
Added a line to rpi-base.inc to get gpio-poweroff overlay.

### PR DESCRIPTION
**Pull request by ckelloug3**
/conf/machine/include/rpi-base.inc: Added gpio-poweroff.dtbo so that this overlay may be used in config.txt

Some systems need to use gpi-poweroff so that a gpio line can be used to control power on the device.
This 1 line patch makes it possible to do it in hardknott.  There doesn't seem to be a way to add an overlay
without modifying this file.

Signed-off-by: Cameron Kellough <cameron@telemetrak.com>

### CODE REVIEW

**Comment by agherzan** [comment]
Thanks @for this. It looks good but we would need to first tweak the commit log to maintain the existing history format. See https://meta-raspberrypi.readthedocs.io/en/latest/contributing.html for more info and `git log` for examples.

**Review by agherzan — CHANGES_REQUESTED** [review]
Please reword your commit log.

**Comment by ckelloug3** [comment]
My apologies for not getting to this yet.  Ill fix it tonight.Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Andrei Gherzan ***@***.***> Date: 11/4/21  12:39 PM  (GMT-08:00) To: agherzan/meta-raspberrypi ***@***.***> Cc: ckelloug3 ***@***.***>, Mention ***@***.***> Subject: Re: [agherzan/meta-raspberrypi] Added a line to rpi-base.inc to get gpio-poweroff overlay. (PR #930) 
@agherzan requested changes on this pull request.

Please reword your commit log.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/agherzan/meta-raspberrypi/pull/930#pullrequestreview-798186835",
"url": "https://github.com/agherzan/meta-raspberrypi/pull/930#pullrequestreview-798186835",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by agherzan** [comment]
Two things:
1. this should be raised first against master and afterwards cherry-picked against other branches so let's do it for master for now
2. can you wrap git log to a reasonable 80 chars?
3. the subject scope/prefix should be`rpi-base.inc` as opposed to `conf/machine/include/rpi-base.inc`.

**Comment by ckelloug3** [comment]
I'm going to create a new pr that correctly raises the change against master.

**Pull request closed without merging**
