### PR TITLE
Accelerated graphics on Raspberry Pi 4

### PR DESCRIPTION
**Pull request by agherzan**
Tested with kmscube and cinematicexperience.

### CODE REVIEW

**Comment by kraj** [comment]
I think Mesa change will need to be redone as I have moved stuff to core but let’s apply this in meantime

**Comment by agherzan** [comment]
That's exactly my plan.

**Comment by aurelian17** [comment]
I just finished testing, everything looks ok for. Kmscube and qt applications are hardware accelerated.

**Comment by kraj** [comment]
@aurelian17 is it just 32bit or also in 64bit mode ?

**Comment by aurelian17** [comment]
I tested 64bit after @agherzan pointed me to this PR. 32bit worked fine for me with the kmsro before.

**Comment by kraj** [comment]
thanks for conforming.

**Comment by gitgonewithwind** [comment]
@agherzan 
thank you so much. I am going to test.

**Comment by NoneTirex** [comment]
@agherzan so my yocto build can support for x265 hardware acceleration for 4k videos?

**Comment by agherzan** [comment]
I haven't tested it but as far as I know, it should.

**Pull request merged**
