### PR TITLE
Update firmware and kernel

### PR DESCRIPTION
**Pull request by pepijndevos**
Fixes https://github.com/raspberrypi/firmware/issues/1051

### CODE REVIEW

**Comment by agherzan** [comment]
@pepijndevos And one more thing: cleanup the merge commit as well (rebase the branch). Thanks once again.

**Comment by pepijndevos** [comment]
Sorry, I'm working towards a tight deadline, so I don't have the bandwidth to go back and learn a bunch of git fu to clean up the mess at this time. I hope you understand. I can do it properly in a few weeks, but it hardly seems worth it for this trivial change.

**Comment by agherzan** [comment]
We do consider them worth it @pepijndevos hench why we still adhere to those guidelines. I'll keep this PR open unless we include it in another one.

**Comment by pepijndevos** [comment]
I woke up with git commands in my head, so there you go.

**Comment by hhromic** [comment]
@agherzan  despite not liking the attitude of the author of this PR, maybe we can start suggesting to use `git commit -s [...]` so git itself adds the signed-off tag automatically in the commit logs. If you agree I can update the guidelines PR accordingly before merging.

Source: <https://git-scm.com/docs/git-commit#git-commit--s>

**Comment by kraj** [comment]
> @agherzan despite not liking the attitude of the author of this PR, maybe we can start suggesting to use `git commit -s [...]` so git itself adds the signed-off tag automatically in the commit logs. If you agree I can update the guidelines PR accordingly before merging.

Please do, although this has a downside where we will force people to sign off on
changes which originated elsewhere so make it clear also what SOB means

> 
> Source: https://git-scm.com/docs/git-commit#git-commit--s

**Comment by pepijndevos** [comment]
Ah, so I'm not completely out of my mind. I was under the impression the signed-off tag was a git feature, and that it would happen semi-automatically.

For the record, I do feel kinda bad about not doing the commit properly, and if it were a more substantial change, I'd be a lot more willing to spend time to do it correctly. This PR could have been an issue "hey, firmware is out of date", and it'd take anyone familiar with the project guidelines under a minute to change it. Instead I pushed the code I already had anyway. I wasn't prepared for all this extra bookkeeping.

**Comment by agherzan** [comment]
@pepijndevos I'm tempted to get into "commit guidelines are not commit size dependent" but I'm sure you know this already. We appreciate and welcome any contribution but they need to adhere, informed or not, to some guidelines to make out life, the maintainers', easier. 

@hhromic @kraj It is actually mentioned in the git command examples for creating email patches. And if that is not enough again, the second paragraph in the oe contribution guidelines mention sob and link this requirement to kernel's 5.4 section where this is explained in detail. In anyway, I do get that this looks like annoying metadata and usually when I join an opensource project I have two options:

1. I blindly copy the format of a past commit (and tweak it for my needs) because I don't have the time to dig into all the details of commit guidelines or I don't really care
2. I am truly interested in the project and I dig into details of these guidelines to understand them and compose a well informed commit log

Both are equally OK in my opinion and I don't think that any information in our own documentation would have helped. That being said though, I'm OK in adding as much as possible to try to avoid these kind of discussions.

**Comment by pepijndevos** [comment]
I definitely fall into the first category. If I'm not deeply involved in a
project, the only place I'm likely to read is the readme. Since this is the
first project I've ever contributed to with such specific commit
guidelines, it might not be a bad idea to put a tldr in the readme.

**Pull request merged**
