### PR TITLE
bluez5: update bluez-firmware

### PR DESCRIPTION
**Pull request by pabigot**
Copied from https://github.com/RPi-Distro/bluez-firmware at commit
50fa5628b5c2fd6c59090fb18f02af9fd98c3170

Documented as from: bluez-firmware_1.2-3+rpt4.1.debian.tar.xz

Signed-off-by: Peter A. Bigot <pab@pabigot.com>

**- What I did**

**- How I did it**

### CODE REVIEW

**Comment by agherzan** [comment]
Is this for rpi3+ support?

**Comment by agherzan** [comment]
ok to test

**Comment by pabigot** [comment]
@agherzan yes, resolves #222 though I didn't put that in the commit message.

**Comment by agherzan** [comment]
Could you please have in the commit log a line which says that this is for rpi3b+ and that it fixes #222? Thanks for this.

**Comment by pabigot** [comment]
@agherzan commit message updated.  I didn't see a standard line for Pi3B+, but it's now mentioned.

**Pull request merged**
