### PR TITLE
gstreamer1.0-omx: Match with oe-core 1.12.x gstreamer

### PR DESCRIPTION
**Pull request by kraj**
Signed-off-by: Khem Raj <raj.khem@gmail.com>

### CODE REVIEW

**Comment by agherzan** [comment]
You were faster. :) I was just testing this.

**Comment by agherzan** [comment]
Fixes https://github.com/agherzan/meta-raspberrypi/issues/111

**Comment by agherzan** [comment]
This still fails with another issue where kernel doesn't find the BSP definition.

**Comment by kraj** [comment]
yeah, there is a problem with OE-Core patch that will have a followup to fix it. Meanwhile you can apply this patch to OE-Core
```
diff --git a/meta/classes/kernel-yocto.bbclass b/meta/classes/kernel-yocto.bbclass
index 3c6df92131..f52b010c70 100644
--- a/meta/classes/kernel-yocto.bbclass
+++ b/meta/classes/kernel-yocto.bbclass
@@ -144,7 +144,7 @@ do_kernel_metadata() {
        # expand kernel features into their full path equivalents
        bsp_definition=$(spp ${includes} --find -DKMACHINE=${KMACHINE} -DKTYPE=${LINUX_KERNEL_TYPE})
        if [ $? -ne 0 ] || [ -z "${bsp_definition}" ]; then
-               bbfatal_log "Could not locate BSP definiton for ${KMACHINE}/${LINUX_KERNEL_TYPE}."
+               bbnote "Could not locate BSP definiton for ${KMACHINE}/${LINUX_KERNEL_TYPE}."
        fi
        meta_dir=$(kgit --meta)
```

**Comment by agherzan** [comment]
I've seen Bruce's reply. Sadly Jenkins tests against master and builds fail now. I'll wait for a fix to be pushed to master in poky before merging stuff here.

**Pull request merged**
