### PR TITLE
Upgrade 4.19 kernel to latest and mark it as default kernel

### PR DESCRIPTION
**Pull request by kraj**

### CODE REVIEW

**Comment by kraj** [comment]
> Nit: s/not/now

fixed

**Comment by agherzan** [comment]
I think we broke rpi1 withe mesa-gl somehow.

**Comment by agherzan** [comment]
On a retrigger it failed on rpi2 as well. Current master seems to build fine.

**Comment by agherzan** [comment]
Erase above - it fails in master as well.

**Comment by kraj** [comment]
I think the build failure is unrelated. but I don't use userland graphics by default so this slipped under my nose. I wonder although if its related to kernel at all. I will try to reproduce it and see whats going on.

**Comment by agherzan** [comment]
@kraj found the issue

```with_dri = _drivers.length() != 0 and _drivers != ['']```

This is because poky switched to meson which does the above to detect dri. In our case, we configure no drivers so no DRI support is added which breaks GBM.

**Comment by kraj** [comment]
cherry-pick  https://patchwork.openembedded.org/patch/161520/ to poky and then this pull will test and work.

**Comment by kraj** [comment]
I have done a dummy change to commit msg to refresh the pull branch so that autobuilder can be retriggered. The relevant patch for mesa-gl has been merged in oe-core see 
https://git.openembedded.org/openembedded-core/commit/?id=0c670a0fad379c3dc2a69ac5abfeaceda98a2f9c

**Comment by agherzan** [comment]
We fixed something and we broke something else:
```

ERROR: No recipes available for:
  /var/lib/jenkins/workspace/meta-raspberrypi-generic/poky/../meta-raspberrypi/recipes-multimedia/gstreamer/gstreamer1.0-omx_1.14%.bbappend
```

**Comment by agherzan** [comment]
Testing a build now with 1.16.x and will push PR.

**Comment by agherzan** [comment]
Merged to master, @kraj . Thanks.

**Pull request merged**
