### PR TITLE
conf/machine/include/rpi-base.inc: Added can1 interface to bsp

### PR DESCRIPTION
**Pull request by colin-pm**
The device tree only supports a single CAN interface.  This prevents
compatiblity with dual-CAN boards like the PiCAN2 Duo.

The mcp2515-can1 device tree blob for overlay was added to RPI_KERNEL_DEVICETREE_OVERLAYS in order to support dual-CAN hats.

Signed-off-by: Colin McAllister <colinmca242@gmail.com>

### CODE REVIEW

**Comment by colin-pm** [comment]
Forgot to add the changes to rpi-config_git.bb for selecting a dual CAN build configuration.  Also felt like the documentation should be updated so I updated the documentation.

**Comment by colin-pm** [comment]
@agherzan commits have been squashed.  Please let me know if they are still unsatisfactory.

**Comment by colin-pm** [comment]
Poke

**Comment by agherzan** [comment]
Git rebase is your friend :) Merged the other PR.

**Pull request closed without merging**
