### PR TITLE
Rocko backports

### PR DESCRIPTION
**Pull request by koenkooi**
Two backports from master for the rocko branch to fix issues I ran into.

### CODE REVIEW

**Comment by agherzan** [comment]
add to whitelist

**Comment by agherzan** [comment]
ok to test

**Comment by agherzan** [comment]
@koenkooi this PR looks to be created against master. Didn't you want to do it for rocko?

**Comment by koenkooi** [comment]
Yes, I forgot to select the right branch, sorry about that, should be fixed now.

**Comment by agherzan** [comment]
Thanks @koenkooi

**Pull request merged**
