### PR TITLE
Dunfell backports from master

### PR DESCRIPTION
**Pull request by agherzan**
This backports all compatible commits from master to dunfell.

### CODE REVIEW

**Comment by shr-project** [comment]
Something seems a bit wrong with this PR, don't you want to target dunfell branch instead of master?

> wants to merge 98 commits into master from dunfell-next

**Comment by agherzan** [comment]
Nice catch @shr-project . Switched to dunfell

**Comment by shr-project** [comment]
Please drop "layer.conf: Add gatesgarth to LAYERSERIES_COMPAT" from this PR as it might just increase confusion about dunfell branch (and will conflict with the dunfell PR from me you just merged)

**Comment by agherzan** [comment]
Fixed. If nobody has any objections until tomorrow, I'll merge it.

**Comment by shr-project** [comment]
"libcamera: Define packageconfig to enable rpi pipeline" commit probably shouldn't have been backported to dunfell.

202002 version in dunfell fails with:
`ERROR: QA Issue: libcamera: configure was passed unrecognised options: pipelines [unknown-configure-option]`
202008 version in gatesgarth is fine, it was added in March:
https://git.linuxtv.org/libcamera.git/commit/meson_options.txt?id=ee7e2c93dfbf34b3500c895115c516e5e90d3e31

I'll send revert shortly.

**Comment by agherzan** [comment]
Ah! This is because I wasn't building with meta-multimedia. "Great"!

**Pull request merged**
