### PR TITLE
linux-raspberrypi-5.10: remove since they have unavailable devicetree's

### PR DESCRIPTION
**Pull request by quaresmajose**
The imx708.dtbo and bcm2711-rpi-cm4s.dtb is not available on the this kernel:

```
# | make[2]: *** No rule to make target 'arch/arm64/boot/dts/overlays/imx708.dtbo'.  Stop.
# | make[2]: *** No rule to make target 'arch/arm64/boot/dts/broadcom/bcm2711-rpi-cm4s.dtb'.  Stop.
```

**- What I did**

**- How I did it**

### CODE REVIEW

**Comment by quaresmajose** [comment]
This will also fail when generating the wic image so the right fix is backporting the dtb's
```
| output: install: cannot stat '/build/deploy/images/raspberrypi4-64/imx708.dtbo': No such file or directory
```

**Comment by quaresmajose** [comment]
The overlays/imx708.dtbo is not supported and backport [1] the dtbo is not accepted so drop this kernel version.
[1] https://github.com/raspberrypi/linux/pull/5452

**Comment by quaresmajose** [comment]
> I am happy to drop this version from master.

I deleted them from my layer some time ago.

**Review by agherzan — APPROVED** [review]

**Review by agherzan — APPROVED** [review]
Looks good!

**Pull request merged**
