### PR TITLE
Fix for wiringpi library that is not linked correctly

### PR DESCRIPTION
**Pull request by aurelian17**
Incorrect order of compiler flags causing the libwiringpi.so library
to not have the required linking dependencies. The cross-compilation
patch needed to be reworked in order to fix issue #105.

Signed-off-by: Aurelian Zanoschi <aurelian17@gmail.com>

**- How I did it:**
The major problems were in the Makefile from wiringPi source tree that is currently patched by 0001-Add-initial-cross-compile-support.patch. I had to fix the problems and rework the patch.

### CODE REVIEW

**Comment by agherzan** [comment]
add to whitelist

**Comment by agherzan** [comment]
test this please

**Comment by agherzan** [comment]
Thanks @aurelian17 for the fix. Could you please tweak the commit log so that it would keep the format used in this repos (http://www.openembedded.org/wiki/Commit_Patch_Message_Guidelines)?

**Comment by agherzan** [comment]
There is though one more change needed. Builds got broken due to a bbappend getting invalid. This was fixed in master. Could you please rebase this PR for the build server to be able to pass the issue currently fixed in master?

**Comment by aurelian17** [comment]
Andrei, can you please push this commit to the stable pyro branch too? Unfortunately that stable branch is affected by this problem too.

Thanks in advance.

**Comment by gizero** [comment]
Was there any attempt to talk to the upstream to get the content of the original/updated patch integrated? It looks like it deals with very generic cross-compile related issues. I had to dig into it months ago while upgrading wiringPi to 2.44 and I forgot what a mess it was. Now, trying to review what was changed by this patch brought back that nasty feeling...

**Comment by agherzan** [comment]
I was surprised to be honest that it didn't happen. @gizero and/or @aurelian17 can any of you work with upstream to fix this?

@aurelian17 you will need to push a PR towards pyro too in order to have it there.

**Comment by gizero** [comment]
At first sight the upstream project's website doesn't even seem to have a contribution guide. Googling for "site:wiringpi.com patch bug contribute" gives no match! :-() Official sources are on a self hosted git repo with no issue tracker I could find. It might be an harder than expected task :-(. Let's see what's @aurelian17's opinion on that..

**Comment by aurelian17** [comment]
Hi, sorry for the delay, just returned from vacation. From my point of view is quite difficult to push this kind of patches to Gordon's repository.

Thanks, @agherzan for accepting this change, I will push it to the pyro branch too.

**Pull request merged**
