### PR TITLE
[hardknott] gstreamer1.0-omx: rename bbappend to match new 1.18.0 version from oe-core

### PR DESCRIPTION
**Pull request by shr-project**
Be aware that this PR could be merged only after branching current master branch as gatesgarth.

Alternatively we can rename the bbappend to be completely version agnostic (as the same patches apply cleanly on 1.16.* and 1.18.*)

On side note LAYERSERIES_COMPAT_raspberrypi = "sumo thud warrior zeus dunfell gatesgarth"
should really be shortened to something people might actively use meta-raspberrypi layer with, e.g. since
36c3c2e7ca09806da460328767565bbf872a6ad8 it probably doesn't even parse with anything older than zeus (where gstreamer was upgraded to 1.16.*)

### CODE REVIEW

**Comment by kraj** [comment]
since we have dunfell branch, I think we should delete all entries up to dunfell in `LAYERSERIES_COMPAT` secondly, I think branching gatesgarth is good idea too.

**Comment by agherzan** [comment]
@kraj shall we keep master for a while and do a late branching when we have incompatible changes? We've done that before and it worked well. It also helps in maintaining while there is nothing incompatible in between master and hardknott.

**Comment by shr-project** [comment]
@agherzan it's not about "nothing incompatible in between master and hardknott." but between gatesgarth and hardknott/master, right now there is no meta-raspberrypi branch compatible with gatesgarth release, that's why gatesgarth has to be branched from commit before this PR was merged.

**Comment by agherzan** [comment]
Shoot. Missed that one. Thanks for pointing it out. I'll branch.

**Comment by agherzan** [comment]
Easy job: https://github.com/agherzan/meta-raspberrypi/tree/gatesgarth. Now I'll merge this in master. Cheers for this.

**Comment by kraj** [comment]
> @kraj shall we keep master for a while and do a late branching when we have incompatible changes? We've done that before and it worked well. It also helps in maintaining while there is nothing incompatible in between master and hardknott.

@agherzan I think we should branch now, since there are these gstreamer changes which we need to accommodate
and I don't like the idea of having multiple versions.

**Comment by agherzan** [comment]
@kraj are you referring to gatesgarth or harnknot?

**Comment by shr-project** [comment]
hardknott branch should be created in +- 6 months, not now, I'm pretty sure he was referring to gatesgarth :)

**Comment by agherzan** [comment]
@shr-project We also need to refresh this PR:

> commit da390c5a3a8a9e7393b59de7abce997bb7d8cba4
> Author: Alexander Kanavin <alex.kanavin@gmail.com>
> Date:   Mon Nov 2 17:48:55 2020 +0100
>     gstreamer1.0: upgrade 1.18.0 -> 1.18.1

**Comment by kraj** [comment]
> > @kraj shall we keep master for a while and do a late branching when we have incompatible changes? We've done that before and it worked well. It also helps in maintaining while there is nothing incompatible in between master and hardknott.
> 
> @agherzan I think we should branch now, since there are these gstreamer changes which we need to accommodate
> and I don't like the idea of having multiple versions.

I am saying to branch `gatesgarth` and master is hardknott as of now.

**Comment by agherzan** [comment]
@kraj That's what I thought. `gatesgarth` was already created. So we are good with that.

**Comment by shr-project** [comment]
@agherzan it's named gstreamer1.0-omx_1.18%.bbappend so it works with current master as well (unless you want me to update commit message to say 1.18.1 instead of 1.18.0.

Or does one of those patches fail to apply on 1.18.1? I need to double check if one of my world build already finished with 1.18.1 in oe-core.

**Comment by agherzan** [comment]
Just give it a sanity check just in case. No need to deal with the commit log if it works.

**Comment by kraj** [comment]
> @agherzan it's named gstreamer1.0-omx_1.18%.bbappend so it works with current master as well (unless you want me to update commit message to say 1.18.1 instead of 1.18.0.
> 
> Or does one of those patches fail to apply on 1.18.1? I need to double check if one of my world build already finished with 1.18.1 in oe-core.

1.18% is fine.

**Comment by shr-project** [comment]
> Just give it a sanity check just in case. No need to deal with the commit log if it works.

only gstreamer1.0 was upgraded, no change in gstreamer1.0-omx, so it should be fine

**Comment by agherzan** [comment]
@shr-project Cheers for the check and PR. Merged.

**Pull request merged**
