### PR TITLE
fixes #465: linux-raspberrypi pull from https by default

### LINKED ISSUE #465: Use https protocol instead of git
The ssh port for git may be blocked on some setups. Using https would be more compatible.

https://github.com/agherzan/meta-raspberrypi/blob/9d0935c9bb1309431e62b8f8341eb503653e5ff5/recipes-kernel/linux/linux-raspberrypi_4.19.bb#L8

### PR DESCRIPTION
**Pull request by saeugetier**
raspberrypi-linux: changed repository source from git to https (https is used by default if protocol is left blank)

Signed-off-by: Timm Eversmeyer saeugetier@gmail.com

### CODE REVIEW

**Comment by agherzan** [comment]
Also rebase on master please.

**Comment by agherzan** [comment]
@saeugetier A friendly reminder on this PR.

**Comment by saeugetier** [comment]
@agherzan thank you for the reminder. I'm quite busy with an other project for now. I think I will fix this next week.

**Comment by agherzan** [comment]
Another friendly ping on this change @saeugetier .

**Comment by saeugetier** [comment]
Create new pull request

**Pull request closed without merging**
