### PR TITLE
linux-raspberrypi: Rename linux.inc to linux-rpi.inc

### PR DESCRIPTION
**Pull request by Herrie82**
Rename linux.inc to prevent it from impacting other machines when building in an environment with multiple machines.

A bit of background: LuneOS is an Open webOS distribution using Yocto and has a build environment for Galaxy Nexus (Maguro), Nexus 4 (Mako), HP Touchpad (Tenderloin), N7 2012 Wifi (Grouper), qemux86 and Raspberry Pi 2 (and soon Raspberry Pi 3). Having the file called linux.inc will impact the build of other target devices.

Signed-off-by: Alan Stice <alan@alanstice.com>
Signed-off-by: Herman van Hazendonk <github.com@herrie.org>

### CODE REVIEW

**Comment by agherzan** [comment]
Hello @Herrie82 . I'm fine with this patch. Would you be able to send this patch to the mailing list too as stated in the README? That would help a lot. Thanks.

**Comment by Herrie82** [comment]
Just did that :) I think we're one of the few projects that build multiple targets using SSTATE, but we had all kinds of weird issues with our other targets when it was linux.inc ;)

**Comment by agherzan** [comment]
Indeed. We do it at resin.io too. We build multiple targets from sstate. But I haven't hit this before as nobody had a kernel.inc file. But I agree that this is indeed a good change. Will merge this from the mailing list.

**Comment by Herrie82** [comment]
I'll get to sort the patch email tonight. I'll try from my Windows GitHub client. Just need to get SSL for the email sorted ;)

**Comment by Herrie82** [comment]
Alan Stice sent it by email yesterday :)

**Comment by agherzan** [comment]
Merged from mailing list.

**Pull request closed without merging**
