### PR TITLE
[pyro] Update to follow master

### PR DESCRIPTION
**Pull request by betafive**
There's no breaking changes on master yet so let's just follow it on pyro for now.

### CODE REVIEW

**Comment by agherzan** [comment]
This needs a rebase.

**Comment by agherzan** [comment]
I know what's going on... @betafive . It's because last time I merged with a merge commit. Obviously it will fail now unless I do the same... I'll do it manually forcing pyro banch. And then I will try to remember to rebase and merge whenever pyro follows up. Sounds good?

**Comment by betafive** [comment]
I think just doing a merge commit at this stage should be fine. I'd avoid force pushing to pyro, I'm already using it and others may be as well so I don't want to break "git pull".

**Comment by agherzan** [comment]
Ok then. Merging.

**Pull request merged**
