### PR TITLE
rpi-config: support more commonly used config variables and update documentation

### PR DESCRIPTION
**Pull request by hhromic**
Added support for and documented the following new extra build options:

* gpu_freq overclocking option
* disable boot rainbow splash screen
* configure the boot delay after GPU firmware loading
* configure common HDMI and composite video options

**- What I did**
Implemented new config.txt options in the `rpi-config` recipe.

**- How I did it**
Followed the same logic in the recipe and added new supported options.
Also updated the documentation.

### CODE REVIEW

**Comment by agherzan** [comment]
ok to test

**Comment by agherzan** [comment]
add to whitelist

**Comment by hhromic** [comment]
thanks for the whitelisting, @agherzan :)
let me know if there is any blocker for merging this PR

**Comment by agherzan** [comment]
@hhromic All good. Merged.

**Pull request merged**
