### PR TITLE
Add support for Raspberry Pi HD quality camera

### PR DESCRIPTION
**Pull request by sss22213**
hi, I create new PR for Raspberry Pi HD quality camera.

### CODE REVIEW

**Review by agherzan — CHANGES_REQUESTED** [review]
Could you add your signed-off-by footer in your commit? See more details https://meta-raspberrypi.readthedocs.io/en/latest/contributing.html.

**Comment by sss22213** [comment]
Hi agherzan,

I add my signed-off-by footer.

Thank you.

**Review by kraj — APPROVED** [review]
lgtm

**Comment by agherzan** [comment]
@agherzan ok to test

**Review by agherzan — APPROVED** [review]

**Review by agherzan — CHANGES_REQUESTED** [review]
@sss22213 can you please rebase your MR (there is a merge commit). I'd also drop the "recipes-bsp:" as this change is in the scope of the entire repository anyway. Otherwise, it looks good to me.

**Review by agherzan — APPROVED** [review]

**Pull request merged**
