### PR TITLE
Update raspberrypi firmware to 20210527

### PR DESCRIPTION
**Pull request by om26er**
Update raspberrypi firmware to 20210527

Signed-off-by: Omer Akram <omer@thing.com>

### CODE REVIEW

**Review by kraj — APPROVED** [review]
LGTM, do we need similar fix for master too first ?

**Comment by agherzan** [comment]
@om26er Can you please first push this against master (as a PR) and afterwards cherry-pick on top of dunfell and update this PR?

**Comment by om26er** [comment]
@agherzan Thanks, I created a PR for master here https://github.com/agherzan/meta-raspberrypi/pull/880

**Comment by agherzan** [comment]
PR for master was merged. We are ready to update this one.

**Comment by om26er** [comment]
> @om26er Can you please first push this against master (as a PR) and afterwards cherry-pick on top of dunfell and update this PR?

Done. However I am not sure if that changed anything in the diff.

**Comment by agherzan** [comment]
Thanks @om26er

**Pull request merged**
