### PR TITLE
libcamera: rename bbappend to match any version

### PR DESCRIPTION
**Pull request by sung-gon-kim**
libcamera has been renamed in meta-openembedded in: 
https://github.com/openembedded/meta-openembedded/commit/1032bce77885f20afb40fff4ed430167c75db59b

This patch is to rename the bbappend to match the recently changed recipe name in the above commit.

### CODE REVIEW

**Comment by tewarid** [comment]
Should we rename bbappend to `libcamera_%.bbappend` to match any upstream package version?

**Comment by sung-gon-kim** [comment]
> Should we rename bbappend to `libcamera_%.bbappend` to match any upstream package version?

I agree. It seems more appropriate to change it as you said. I will update the PR. Thanks.

**Review by agherzan — CHANGES_REQUESTED** [review]
@sung-gon-kim Can we squash the commit? I don't see the value of an intermediate commit here.

**Comment by sung-gon-kim** [comment]
@agherzan Oh, sorry. I will squash the commit.

**Review by sung-gon-kim — COMMENTED** [review]
I've squashed the commits and update the PR title.

**Comment by shr-project** [comment]
LGTM

**Review by agherzan — APPROVED** [review]

**Comment by shr-project** [comment]
@agherzan Please create langdale branch before this PR is merged, this will be the first change for mickledore (incompatible with meta-oe/langdale).

**Comment by agherzan** [comment]
> @agherzan Please create langdale branch before this PR is merged, this will be the first change for mickledore (incompatible with meta-oe/langdale).

Why would this be incompatible?

**Comment by shr-project** [comment]
> Why would this be incompatible?

Because of the filename.

libcamera_%.bbappend won't work with libcamera.bb (before rename from https://github.com/openembedded/meta-openembedded/commit/1032bce77885f20afb40fff4ed430167c75db59b)

**Comment by agherzan** [comment]
@shr-project all done.

**Pull request merged**
