### PR TITLE
Add MCP3008 ADC overlay

### PR DESCRIPTION
**Pull request by jclsn**
This adds the overlay for the MCP3008 ADC.

### CODE REVIEW

**Review by kraj — APPROVED** [review]
Lgtm

**Comment by jclsn** [comment]
Didn’t go through? Hmm, works for me

**Review by agherzan — CHANGES_REQUESTED** [review]
Thanks for this @jclsn. You missed the SoB (signed off by line) and also I'd tweak a bit the commit subject: `rpi-base.inc: Add MCP3008 ADC overlay`.

**Comment by agherzan** [comment]
I have included this change in https://github.com/agherzan/meta-raspberrypi/pull/1053. Closing.

**Comment by jclsn** [comment]
@agherzan Ah, did not know about the SoB. Will try to remember it next time!

Lately I have been getting this error

```
ERROR: healthpi-image-1.0-r0 do_image_rpi_sdimg: mcopy cannot copy /home/claussenj/Workspace/Yocto/healthpi/build/tmp/deploy/images/raspberrypi4-64/mcp3008.dtbo into boot.img
ERROR: healthpi-image-1.0-r0 do_image_rpi_sdimg: ExecutionError('/home/claussenj/Workspace/Yocto/healthpi/build/tmp/work/raspberrypi4_64-poky-linux/healthpi-image/1.0-r0/temp/run.do_image_rpi_sdimg.802539', 1, None, None)
ERROR: Logfile of failure stored in: /home/claussenj/Workspace/Yocto/healthpi/build/tmp/work/raspberrypi4_64-poky-linux/healthpi-image/1.0-r0/temp/log.do_image_rpi_sdimg.802539
ERROR: Task (/home/claussenj/Workspace/Yocto/healthpi/sources/meta-healthpi/recipes-healthpi/images/healthpi-image.bb:do_image_rpi_sdimg) failed with exit code '1
``` 

No idea what I did, but somehow it can't add the blob to the image anymore. Any idea why?

**Comment by agherzan** [comment]
What machine are you building for and what revisions of the layers?

**Comment by jclsn** [comment]
I think I found the issue. The above error only occurs when I explicitly append the blob to ``RPI_KERNEL_DEVICETREE_OVERLAYS``. When I remove that line from my ``local.conf```it works. I wonder why though. Like this it is in there twice, but that shouldn't make a difference from my understanding.

I also have an issue with creating my own image. The splash screen is gone, although it is listed in ``SPLASH``. Can I get support from you on this? It is not part of this topic. I also have another issue regarding libGL again, although I thought that I fixed it. Been trying for weeks to get my project to work on the Pi.

**Pull request closed without merging**
