### PR TITLE
rpio: Add RDEPENDS For python-logging & python-threading

### PR DESCRIPTION
**Pull request by TafThorne**
[GitHub Ticket #98 - rpio requires the logging and threading Python
packages but does not RDEPENDS them in recipe]

The rpio tool needs the Python logging and threading packages installed
on the target system for it to work.  The packages are not included when
doing a rpi-basic-image.  This change updates the recipe so that all the
required dependencies of the rpio script are identified by the recipie.

Signed-off-by: Thomas A F Thorne <TafThorne@GoogleMail.com>

**- What I did**

Ensured all dependencies are met for the prio script.  

**- How I did it**

Updated the recipe to indicate the missing dependencies.

### CODE REVIEW

**Comment by TafThorne** [comment]
I am working against a Krogoth target so if this change could be backported that far I would be greatful.  I can work around things if that is not possible though.

**Comment by betafive** [comment]
Could you rebase this on top of the current master so that it can be merged? We should be able to look at backporting after it's been merged - I personally think that if it's an obvious fix for an observed issue then it should be possible to backport it to krogoth even though that's no longer actively maintained.

**Comment by TafThorne** [comment]
Update / Rebase done.

**Comment by agherzan** [comment]
Can you please rebase on top of master so we avoid the merge commit? As well please follow the summary convention for git logs https://github.com/agherzan/meta-raspberrypi/blob/master/docs/contributing.md#patches-and-pull-requests .

**Comment by TafThorne** [comment]
> Can you please rebase on top of master so we avoid the merge commit? 

I am sure I did that already but I will check again.  

> As well please follow the summary convention for git logs https://github.com/agherzan/meta-raspberrypi/blob/master/docs/contributing.md#patches-and-pull-requests

I have done that.  Please can you give an example of where I deviated from the instruction?  

```
  Short log / Statement of what needed to be changed.
  
  (Optional pointers to external resources, such as defect tracking)
  
  The intent of your change.
  
  (Optional, if it's not clear from above) how your change resolves the
  issues in the first part.
  
  Tag line(s) at the end.
```

I put exactly that into the commit message then I completed the form provided by GitHub when making the pull request.  My references to this GitHub issue are at the top.  I stated the intent of my change and I felt that adding RDEPENDS was quite a clear resolution of the change and did not need any further wording.

**Comment by agherzan** [comment]
I see the confusion now. We should clarify this in the docs. If you check git history we use the example as the format "foobar: Adjusted the foo setting in bar". So you will have something like "recipe/bbclass/component: Short summary" as subject line.

About the rebase this PR still has a merge commit.

**Comment by TafThorne** [comment]
So in this case it would be "rpio: Add RDEPENDS For python-logging & python-threading"? 

As with about half my interactions with `git rebase` everything is now a terrible mess full of merge conflicts.  I am certainly in the camp of hating it far more than some messy (but accurate) history.  I will try and resolve the conflicts.  Currently I am looking at `linux-raspberrypi_4.4.bb: support for .dtbo files for dtb overlays` but I have no idea why it thinks I should be resolving all this.

**Comment by TafThorne** [comment]
Oh now what have I done...

**Comment by agherzan** [comment]
Ouch. :) You will manage it.

The proposed commit log looks good.

**Comment by TafThorne** [comment]
I hit the "doing as the instructions tell me instead of what every one does" problem quite frequently.  The rebase issues tend to crop up two or three times with every new project I touch until I work out how rebasing works on this workflow.  I am sure I'll figure it out in the end...

**Comment by TafThorne** [comment]
I have no idea how to rebase this... do I have to checkout this pull request branch and rebase that instead?

**Comment by agherzan** [comment]
The simplest way that I can come out with now is:

1. `git fetch --all`
2. `git checkout -f origin/master -b rpio-depends`
3.  `git cherry-pick ABC` - only the commit which adds the RDEPENDS
4.  `git push origin rpio-depends -f`

**Comment by TafThorne** [comment]
```
$ git checkout -f origin/master -b rpio-depends
fatal: Cannot update paths and switch to branch 'rpio-depends' at the same time.
Did you intend to checkout 'origin/master' which can not be resolved as commit?
```

I had started saying: 
> This change was based on krogoth.  I cannot rebase it to master as the history is too scrambled between the two (probably thanks to rebasing backports instead of starting them at the old one and pulling through).  I can drop this pull request, branch and checkin on my remote branch and start again based on master instead.  Unless someone else can suggest a different solution?

**Comment by TafThorne** [comment]
```
$ git remote show
taft
yoctop
```
I am not sure if it is me or you that made the remote yoctop.  Probably me if I checked out my copy then had to work out an upstream.  

```
$ git checkout -f yoctop/master -b rpio-depends
fatal: A branch named 'rpio-depends' already exists.
```
urg

```
$ git checkout -f yoctop/master -b rpio-depends2
Branch rpio-depends2 set up to track remote branch master from yoctop.
Switched to a new branch 'rpio-depends2'
```
There.  

```
 git cherry-pick e2bd7763a1c8de55a52a45ee06f97acade6dadb1
[rpio-depends2 a5cf6c4] Add RDEPENDS To rpio For python-logging & python-threading
 Date: Mon Jul 24 10:48:00 2017 +0100
 1 file changed, 5 insertions(+)
``` 
Looking hopeful.

**Comment by TafThorne** [comment]
Now by origin in that last push I did taft.

**Comment by TafThorne** [comment]
This still all looks rather not like what you want though.

**Comment by TafThorne** [comment]
What in the world is going on? 
```
$ git status
On branch rpio-depends2
Your branch is ahead of 'yoctop/master' by 1 commit.
  (use "git push" to publish your local commits)
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	recipes-devtools/python/rpio/RPIO-2.0.0b1.tar.gz
	recipes-devtools/python/rpio_2.0.0.bb
	recipes-kernel/linux/linux-raspberrypi_4.4_BACKUP_25001.bb
	recipes-kernel/linux/linux-raspberrypi_4.4_BACKUP_25151.bb
	recipes-kernel/linux/linux-raspberrypi_4.4_BACKUP_26176.bb
	recipes-kernel/linux/linux-raspberrypi_4.4_BASE_25001.bb
	recipes-kernel/linux/linux-raspberrypi_4.4_BASE_25151.bb
	recipes-kernel/linux/linux-raspberrypi_4.4_BASE_26176.bb
	recipes-kernel/linux/linux-raspberrypi_4.4_LOCAL_25001.bb
	recipes-kernel/linux/linux-raspberrypi_4.4_LOCAL_25151.bb
	recipes-kernel/linux/linux-raspberrypi_4.4_LOCAL_26176.bb
	recipes-kernel/linux/linux-raspberrypi_4.4_REMOTE_25001.bb
	recipes-kernel/linux/linux-raspberrypi_4.4_REMOTE_25151.bb
	recipes-kernel/linux/linux-raspberrypi_4.4_REMOTE_26176.bb

nothing added to commit but untracked files present (use "git add" to track)

$ git log -2
commit a5cf6c405957cc2f37f33382cedcdde455bb4015
Author: Thomas Thorne <Thomas.Thorne@Net2Edge.com>
Date:   Mon Jul 24 10:48:00 2017 +0100

    Add RDEPENDS To rpio For python-logging & python-threading
    
    [GitHub Ticket #98 - rpio requires the logging and threading Python
    packages but does not RDEPENDS them in recipie]
    
    The rpio tool needs the Python logging and threading pacakges installed
    on the target system for it to work.  The pacakges are not included when
    doing a rpi-basci-image.  This change updates the recipe so that all the
    required dependencies of the prio script are identified by the recipie.
    
    Signed-off-by: Thomas A F Thorne <TafThorne@GoogleMail.com>

commit 1e1b50c55dd5d1eba5e6fda17f9176127ee6ac5d
Author: Andrea Galbusera <gizero@gmail.com>
Date:   Fri Jul 14 10:44:40 2017 +0200

    userland: Add missing EGL_CAST defines
    
    Needed by libepoxy
    
    Signed-off-by: Andrea Galbusera <gizero@gmail.com>
$ git push taft rpio-depends
Username for 'https://github.com': TafThorne
Password for 'https://TafThorne@github.com': 
Everything up-to-date
```
The git status says things are behind but git push says it is up to date?

**Comment by TafThorne** [comment]
Right I think the best thing I can do is start this pull request again based on Master.  I'll do that in a couple of minutes before I get distracted onto other things.

**Comment by TafThorne** [comment]
Raised pull request #100 as a replacement for this rather messed up one.  Closing this one.

**Pull request closed without merging**
