### PR TITLE
Add hifiberry-dacplusadc overlay

### PR DESCRIPTION
**Pull request by JDavidsson**
Add hifiberry-dacplusadc.dtbo that was missing from the list.

### CODE REVIEW

**Review by agherzan — CHANGES_REQUESTED** [review]
Hello, and thanks for your contribution. Could you please follow the project's contribution guidelines? https://meta-raspberrypi.readthedocs.io/en/latest/contributing.html Checking the git history will give you examples relevant to that specific file.

**Comment by JDavidsson** [comment]
Hi, sorry about that. Updated the commit message, hope it suffices.

**Comment by kraj** [comment]
> Hi, sorry about that. Updated the commit message, hope it suffices.

it would be good if you rebased you branch and removed local merge commits to keep the public repo history clean, we just need patch commits

**Review by agherzan — APPROVED** [review]
Looks good. Thanks!

**Pull request merged**
