### PR TITLE
rpio: Use pypi.bbclass

### LINKED ISSUE #146: fetch form pypi.python.org failed:  ERROR 403: SSL is required.
**Description**

http: URIs are used in the recipes below, but no longer accepted by server. Changing to https will fix this.

**Steps to reproduce the issue:**
using pyro branch of meta-raspberry
1. $ bitbake -c fetch rpi-gpio
2. $ bitbake -c fetch rpio

**Describe the results you received:**
server complaines: ERROR 403: SSL is required.

**Describe the results you expected:**
the source is fetched.

**Additional information you deem important (e.g. issue happens only occasionally):**
seems to be fixed in master by inheriting pypi
could you please add the missing s for pyro too

**Additional details (revisions used, host distro, etc.):**

### PR DESCRIPTION
**Pull request by benierc**
This should resolve recent issues with the non-https URL in SRC_URI. 
fixes #146

Signed-off-by: Paul Barker <pbarker@toganlabs.com>

**- What I did**

**- How I did it**

### CODE REVIEW

**Comment by betafive** [comment]
ok to test.

**Comment by betafive** [comment]
I usually like to group backports together into batches but this one is simple.

**Comment by benierc** [comment]
Ok, no problem. 
I just cherry pick your commit from master because fetch rpio failed in rocko.
I might have open an issue.

**Comment by betafive** [comment]
Have you tested rpio builds on rocko branch with this change? If so I'll merge this as soon as Jenkins has done its build tests.

**Comment by agherzan** [comment]
Looks good.

**Pull request merged**
