### PR TITLE
linux-firmware: Update brcmfmac43430 to 7.45.41.46

### PR DESCRIPTION
**Pull request by agherzan**
**- What I did**
The version of this firmware provided by linux-firmware is 7.45.41.26. This
version seems to have connectivity issues when bonding interfaces. Raspbian
included an updated version (7.45.41.46) which tested proved to fix this
problem (see https://github.com/resin-os/meta-resin/issues/812).

The version Raspbian is providing is not yet in linux-firmware as they have it
directly from Cypress (see https://github.com/RPi-Distro/repo/issues/88).
Besides the issue described above, it fixes various other issues including a
broadpwn fix.

Hopefully this version, or a newer one, will end up in upstream soon. In order
to catch when that happens and stop overwriting this firmware, a check is added
in the racipe based on the md5sum of the current shipped firmware.

In terms of ditribution license, we got an informal one in the github thread
mentioned above.

**- How I did it**
Include the new firmware version in this yocto BSP layer.

### CODE REVIEW

**Comment by agherzan** [comment]
@betafive do you plan a PR on pyro? Can we have this there too?

**Comment by betafive** [comment]
Sorry for the delay - I'm lacking internet in my office at the minute :(

This PR looks good though. I'll look at pyro backports tomorrow.

**Comment by agherzan** [comment]
Cheers @betafive .

**Comment by agherzan** [comment]
@willnewton keep an eye on this when it arrives in pyro. I know you are interested.

**Pull request merged**
