### PR TITLE
Add initial cross compile support 

### PR DESCRIPTION
**Pull request by LocutusOfBorg**
(rebase from Petter Mabäcker <petter@technux.se> version)

Hi, this is my first contribution, I hope you will find it useful :)

### CODE REVIEW

**Comment by agherzan** [comment]
Hello @LocutusOfBorg ,

First if all thank you for you contribution. Could you please use the README file for instructions on how to submit patches? That would help. For this specific one I will modify it myself. Thanks.

**Comment by LocutusOfBorg** [comment]
Hi @agherzan well, I read the README file, I was wondering about sending patches by mail, after I discovered this repository and some open pull requests, so I tried to open one too.

I can try to send the patch by mail too, this is the first time I do it, so please forgive me if I miss anything :)
thanks!

**Comment by agherzan** [comment]
It's fine @LocutusOfBorg . As I said for this specific one I will test and merge manually. The important thing is that you understand how we handle contributions. 

P.S.: Got merged.

Thanks once again.
Andrei

**Comment by LocutusOfBorg** [comment]
thanks! I just installed git send-email, I'll see for the next time how to use it :)

**Comment by agherzan** [comment]
Cheers!

**Pull request closed without merging**
