### PR TITLE
Update rpi-eeprom to support raspberrypi5 machine

### PR DESCRIPTION
**Pull request by mast**
- Upgraded rpi-eeprom to latest release
 - Updated recipe to support pi4 and pi5 machines

### CODE REVIEW

**Review by kraj — APPROVED** [review]
lgtm

**Comment by mast** [comment]
@kraj do you want me to push new commit with signoff?

**Comment by kraj** [comment]
> @kraj do you want me to push new commit with signoff?

Oh yes please !

**Comment by agherzan** [comment]
Looks good! Thanks. Kicked off CI and auto-merge.

**Comment by mast** [comment]
@kraj  @agherzan  I'm so sorry guys, I signed-off my prev commit with wrong email, ugh. It should be ok now.

**Comment by agherzan** [comment]
Now that we already interrupted CI, can you also tweak a bit the git log summary line?

`rpi-eeprom: Update to support raspberrypi5 machine`

**Comment by mast** [comment]
@agherzan sure thing, updated.

**Comment by agherzan** [comment]
Thanks, @mast. I have triggered CI and auto-merge on success.

**Pull request merged**
