### PR TITLE
linux-firmware: remove duplicate ${PN}-bcm43455 package

### PR DESCRIPTION
**Pull request by shr-project**
This is the rest of https://github.com/agherzan/meta-raspberrypi/pull/295 it also depends on oe-core changes which aren't in master yet, but as of today they are in master-next.
http://lists.openembedded.org/pipermail/openembedded-core/2018-July/153164.html
http://lists.openembedded.org/pipermail/openembedded-core/2018-July/153167.html

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>

### CODE REVIEW

**Comment by shr-project** [comment]
The changes just landed in oe-core/master, this is now needed to get successful build again.

**Comment by shr-project** [comment]
Without this the builds are failing with:
ERROR: linux-firmware-1_0.0+gitAUTOINC+d114732723+86e88fbf03+e28cd7ee86-r0 do_package: QA Issue: linux-firmware-bcm43455 is listed in PACKAGES multiple times, this leads to packaging errors. [packages-list]

**Comment by hhromic** [comment]
Can confirm all of @shr-project's reports. Merging this PR is the only thing missing now after the firmware license changes.

**Comment by agherzan** [comment]
@shr-project @hhromic I was just about to get to it and fix it. Really helpful. Thanks guys!

**Pull request merged**
