### PR TITLE
Openlabs 802.15.4 hat support

### PR DESCRIPTION
**Pull request by OYTIS**
Support added for Openlabs 802.15.4 header. Kernel modules were already enabled, so the PR is just about installing and loading the respective device tree overlay. Tested on RPi3B+

### CODE REVIEW

**Comment by betafive** [comment]
Could you add a short description in `docs/extra-build-config.md` so people can find out about this from the docs?

**Comment by OYTIS** [comment]
@betafive Sure, done.

**Comment by betafive** [comment]
ok to test

**Comment by betafive** [comment]
LGTM now, let's see what Jenkins says.

**Pull request merged**
