### PR TITLE
Fix WiFi driver loading on CM4

### PR DESCRIPTION
**Pull request by om26er**
This change is required for the Wifi to work on the CM4

Will do a cherry pick for the dunfell branch once this lands.

### CODE REVIEW

**Review by kraj — DISMISSED** [review]
lgtm

**Review by agherzan — CHANGES_REQUESTED** [review]
Thanks @om26er. This looks good. Could you please just tweak your commit log in accordance with https://meta-raspberrypi.readthedocs.io/en/latest/contributing.html? That would help. Something like: "linux-firmware-rpidistro: Fix WiFi...." and also include your Signed-off-by line.

**Comment by om26er** [comment]
> Something like: "linux-firmware-rpidistro: Fix WiFi...." and also include your Signed-off-by line.

This is done now

**Comment by agherzan** [comment]
@agherzan-ci ok to test

**Comment by om26er** [comment]
ping ?

**Comment by agherzan** [comment]
@om26er you introduced a merge commit. Could you clean it up by rebasing it on top of master?

**Review by agherzan — APPROVED** [review]

**Comment by om26er** [comment]
@agherzan Fixed. Can you please check if it looks good now

**Comment by agherzan** [comment]
@om26er All good. Will merge as soon as CI thumbs up.

**Pull request merged**
