### PR TITLE
linux: Enable Broadcom STB I2C bus driver

### PR DESCRIPTION
**Pull request by eigendude**
**- What I did**

This PR enables the Broadcom STB I2C bus driver in the kernel config.

Without this change, when I enable the GPU on my Pi 4, my HDMI TFT display shows U-boot doing its thing then goes blank.

Enabling the STB I2C bus fixes the problem by letting Linux communicate through the Display Data Channel (DDC) to allow the TFT display to work.

**- How I did it**

I enabled the CONFIG_I2C_BRCMSTB option in vc4graphics.cfg to ensure proper support for the `brcm,bcm2711-hdmi-i2c` device node.

Without this configuration, the I2C bus associated with HDMI on Broadcom BCM2711-based systems may fail to probe, causing issues with HDMI communication and display initialization.

Additionally, this resolves potential deferred probe issues observed in the kernel logs, ensuring the correct initialization of the HDMI I2C bus.

### CODE REVIEW

**Review by agherzan — APPROVED** [review]
Thanks. Looks good to me.

**Comment by agherzan** [comment]
Merged. Thanks for this.

**Comment by eigendude** [comment]
I'm currently working on `scarthgap`, would you like a backport of this?

**Comment by agherzan** [comment]
@eigendude A clean cherry-pick would be nice indeed. Thanks!

**Pull request merged**
