### PR TITLE
sdcard_image-rpi: fix absolute path in vfat symlink

### PR DESCRIPTION
**Pull request by gizero**
Fix bitbake complaining with:

ERROR: core-image-minimal-1.0-r0 do_image_complete: sstate found an absolute
path symlink [...].vfat pointing at [...].vfat. Please replace this with a
relative link.

Signed-off-by: Andrea Galbusera <gizero@gmail.com>

### CODE REVIEW

**Comment by mattsm** [comment]
This looks OK to me

**Comment by agherzan** [comment]
Test this please

**Comment by agherzan** [comment]
I don't understand how this fixes the issue. The PR changes the copy command of a file (U-boot)  not the symlink creation. I'm not sure how this fixes your problem. Could you please detail?

**Comment by gizero** [comment]
The change to `SDIMG_VFAT` value assignment does the trick... Now `ln` will target a relative path instead of an absolute one

**Comment by gizero** [comment]
PR updated by rebasing onto latest master and rewording the commit message to add more details as per my previous comment

**Comment by agherzan** [comment]
Looks good. I will merge it as soon as the builds will get unblocked.

**Comment by agherzan** [comment]
test this please

**Comment by agherzan** [comment]
There is though one more change needed. Builds got broken due to a bbappend getting invalid. This was fixed in master. Could you please rebase this PR for the build server to be able to pass the issue currently fixed in master?

**Comment by gizero** [comment]
This was rebased on current master... Can you please trigger testing the PR?

**Comment by agherzan** [comment]
Sure. @gizero

**Comment by agherzan** [comment]
ok to test

**Comment by gizero** [comment]
Yet rebased on top of Paul's patch to u-boot you merged yesterday... I was wandering what the expected workflow is when there are multiple pending PRs in order to avoid confusion and saving you from triggering too many CI checks. Do you expect the authors to janitor their PRs and keep them rebased while other pending PRs get merged or is it good practice to wait for maintainers to explicitly request rebasing? Moreover what is the preferred workflow for getting PRs up to date with master? I generally like "rebase" approach most, which IMHO gives a more readable histories, but I noticed you used ( i.e. for #114 ) the GitHub provided "Update branch" way, which does a merge of master on the PR branch...

**Comment by agherzan** [comment]
For whatever reason it didn't allow me to update. Even though I can't see a conflict. Anyway. I'll use it now :) . Thanks for this.

**Pull request merged**
