### PR TITLE
Small cleanup of KERNEL_DEFCONFIG

### PR DESCRIPTION
**Pull request by shr-project**
Small cleanup of KERNEL_DEFCONFIG.

### CODE REVIEW

**Comment by betafive** [comment]
I found that these changes lead to a build error when not using u-boot (`RPI_USE_U_BOOT = "0"`) with `MACHINE = "raspberrypi3-64"`.

```
ERROR: linux-raspberrypi-1_4.9.59+gitAUTOINC+e7976b2aff-r0 do_compile: oe_runmake failed
ERROR: linux-raspberrypi-1_4.9.59+gitAUTOINC+e7976b2aff-r0 do_compile: Function failed: do_compile (log file is located at /home/pbarker/oryx/build/tmp/work/raspberrypi3_64-oe-linux-musl/linu
x-raspberrypi/1_4.9.59+gitAUTOINC+e7976b2aff-r0/temp/log.do_compile.18196)
ERROR: Logfile of failure stored in: /home/pbarker/oryx/build/tmp/work/raspberrypi3_64-oe-linux-musl/linux-raspberrypi/1_4.9.59+gitAUTOINC+e7976b2aff-r0/temp/log.do_compile.18196
Log data follows:
| DEBUG: Executing shell function do_compile
| NOTE: make -j 8 HOSTCC=gcc  -isystem/home/pbarker/oryx/build/tmp/work/raspberrypi3_64-oe-linux-musl/linux-raspberrypi/1_4.9.59+gitAUTOINC+e7976b2aff-r0/recipe-sysroot-native/usr/include -O2
 -pipe -L/home/pbarker/oryx/build/tmp/work/raspberrypi3_64-oe-linux-musl/linux-raspberrypi/1_4.9.59+gitAUTOINC+e7976b2aff-r0/recipe-sysroot-native/usr/lib -L/home/pbarker/oryx/build/tmp/work/
raspberrypi3_64-oe-linux-musl/linux-raspberrypi/1_4.9.59+gitAUTOINC+e7976b2aff-r0/recipe-sysroot-native/lib -Wl,-rpath-link,/home/pbarker/oryx/build/tmp/work/raspberrypi3_64-oe-linux-musl/lin
ux-raspberrypi/1_4.9.59+gitAUTOINC+e7976b2aff-r0/recipe-sysroot-native/usr/lib -Wl,-rpath-link,/home/pbarker/oryx/build/tmp/work/raspberrypi3_64-oe-linux-musl/linux-raspberrypi/1_4.9.59+gitAU
TOINC+e7976b2aff-r0/recipe-sysroot-native/lib -Wl,-rpath,/home/pbarker/oryx/build/tmp/work/raspberrypi3_64-oe-linux-musl/linux-raspberrypi/1_4.9.59+gitAUTOINC+e7976b2aff-r0/recipe-sysroot-nat
ive/usr/lib -Wl,-rpath,/home/pbarker/oryx/build/tmp/work/raspberrypi3_64-oe-linux-musl/linux-raspberrypi/1_4.9.59+gitAUTOINC+e7976b2aff-r0/recipe-sysroot-native/lib -Wl,-O1 HOSTCPP=gcc  -E zI
mage CC=aarch64-oe-linux-musl-gcc   -fuse-ld=bfd  --sysroot=/home/pbarker/oryx/build/tmp/work/raspberrypi3_64-oe-linux-musl/linux-raspberrypi/1_4.9.59+gitAUTOINC+e7976b2aff-r0/recipe-sysroot
-ffile-prefix-map=/home/pbarker/oryx/build/tmp/work-shared/raspberrypi3-64/kernel-source=/kernel-source/  LD=aarch64-oe-linux-musl-ld.bfd    --sysroot=/home/pbarker/oryx/build/tmp/work/raspbe
rrypi3_64-oe-linux-musl/linux-raspberrypi/1_4.9.59+gitAUTOINC+e7976b2aff-r0/recipe-sysroot LOADADDR=0x00008000
|   GEN     ./Makefile
| scripts/kconfig/conf  --silentoldconfig Kconfig
| make[2]: *** No rule to make target 'zImage'.  Stop.
| Makefile:150: recipe for target 'sub-make' failed
| make[1]: *** [sub-make] Error 2
| Makefile:24: recipe for target '__sub-make' failed
| make: *** [__sub-make] Error 2
| ERROR: oe_runmake failed
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_compile (log file is located at /home/pbarker/oryx/build/tmp/work/raspberrypi3_64-oe-linux-musl/linux-raspberrypi/1_4.9.59+gitAUTOINC+e7976b2aff-r0/temp/log.do_co
mpile.18196)
ERROR: Task (/home/pbarker/oryx/meta-raspberrypi/recipes-kernel/linux/linux-raspberrypi_4.9.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 1170 tasks of which 810 didn't need to be rerun and 1 failed.
```

**Comment by shr-project** [comment]
I'm sorry about the issue, as mentioned in the comment before I haven't tested all possible configurations (I know I should at least with bitbake -e..)

I'm working on a bit cleaner solution for installing the DTB files, but that will need corresponding change in oe-core's kernel-devicetree.bbclass.

**Comment by betafive** [comment]
@shr-project, no worries, I have a potential solution I'm testing at the minute.

**Comment by agherzan** [comment]
@betafive Any update on uboot configuration?

**Comment by betafive** [comment]
@agherzan, The fix I subitted in PR #158 handles the u-boot configuration problems I was seeing. This PR is now just KERNEL_DEFCONFIG clean-ups which look good.

**Comment by agherzan** [comment]
That's what I was suspecting. Cool.

**Pull request merged**
