### PR TITLE
[kirkstone] udev-rules-rpi: Use 99-com.rules directly from upstream

### PR DESCRIPTION
**Pull request by floion**
Rather than have an unsynchronized copy of this file, let's use this udev rule directly from upstream.

**- What I did**

**- How I did it**

### CODE REVIEW

**Comment by floion** [comment]
@agherzan I've opened this PR to be backported to kirkstone and also 2 other backports for langdale https://github.com/agherzan/meta-raspberrypi/pull/1187 and mickledore https://github.com/agherzan/meta-raspberrypi/pull/1188

**Comment by floion** [comment]
@agherzan anything to make it kick off these stalled checks?

**Comment by agherzan** [comment]
These are most probably builds on cold cache and we don't have any parallelism on the CI so it will take a while. I'll enable auto merge so as soon as it passes we'll have it merged.

**Review by agherzan — APPROVED** [review]

**Comment by floion** [comment]
Thanks @agherzan

**Comment by floion** [comment]
@agherzan can we re-run the failing tests?

**Pull request merged**
