### PR TITLE
Rocko Backports

### PR DESCRIPTION
**Pull request by betafive**
Apologies these are so late, things have been busy!

## Changes

Changes to the kernel and firmware are backported along with a couple of other minor fixes.

I've left out the following which could be candidates for backporting. These aren't really things I use heavily though so advice and testing from others would probably be needed to help here:
* bluez5
* userland
* linux-firmware-raspbian

## Testing

I've booted tested on all RPi variants I have but that doesn't include an RPi 3 B+.

Testing from anyone with access to an RPi 3 B+ would be much appreciated! Otherwise you'll all have to wait for me to order one some time next week. I wanted to make sure people see some progress here though as I know I'm a bit behind on backports.

### CODE REVIEW

**Comment by davidweisgerber** [comment]
Hi, for me it boots to raspberry pi 3b+ using my custom image (with all sort of Qt 5 stuff and eglfs)
Bluetooth is working but WiFi does not.

**Comment by davidweisgerber** [comment]
I found the firmware for the WiFi seems to be working. I will continue testing.
Found a bug: reboot is not working

**Comment by davidweisgerber** [comment]
Reboot problem was due to upgrading the build system. For me now it works now

**Comment by betafive** [comment]
Thanks for the testing!

**Pull request merged**
