### PR TITLE
layer.conf: Add warrior to compatible release series

### PR DESCRIPTION
**Pull request by kraj**
Signed-off-by: Khem Raj <raj.khem@gmail.com>

### CODE REVIEW

**Comment by shr-project** [comment]
Is someone still using master branch of meta-raspberrypi with sumo/thud? Shouldn't the older releases be removed once the warrior release settles a bit?

**Comment by kraj** [comment]
Yes, although it should be done sequentially, meaning send a patch to remove older branches as a followup once warrior is working ok

**Comment by kraj** [comment]
@agherzan this needs to be merged asap

**Comment by agherzan** [comment]
Why do we want to remove old branches? I'm pretty sure there are still people working on older yocto releases.

**Comment by kraj** [comment]
Idea is that they are then forced to use the right branch but lets do that as a follow up.

**Pull request merged**
