### PR TITLE
Convert to new override syntax

### PR DESCRIPTION
**Pull request by agherzan**
**- What I did**

converting the metadata to use ":" as the override character instead of
"_".

**- How I did it**

`scripts/contrib/convert-overrides.py` and manual inspection (as the script is not perfect).

### CODE REVIEW

**Comment by shr-project** [comment]
Your version is missing quite a few cases, see https://github.com/agherzan/meta-raspberrypi/pull/886

**Comment by kraj** [comment]
> Your version is missing quite a few cases, see #886

yeah lets go with earlier version from Martin

**Comment by dev-0x7C6** [comment]
Wow, is this something new from recent bitbake revisions? Is it compatible with hardknott release (bitbake 1.50.0?) ?

**Comment by agherzan** [comment]
I found them too in the meanwhile @shr-project. I'm sorry, I completely missed your PR. I'll close this in its favour.

**Comment by shr-project** [comment]
> Wow, is this something new from recent bitbake revisions? Is it compatible with hardknott release (bitbake 1.50.0?) ?

yes, read oe-architecture ML:
https://lists.openembedded.org/g/openembedded-architecture/message/1291

and yes it's compatible with bitbake 1.46 and newer:
https://lists.openembedded.org/g/openembedded-architecture/message/1304

but with meta-raspberrypi master branch you should use bitbake master as well (which is not only compatible with this new syntax, but enforces it).

**Pull request closed without merging**
