### PR TITLE
Backports for gatesgarth

### PR DESCRIPTION
**Pull request by ricardosalveti**
Gatesgarth is currently behind in terms of the kernel and firmware revision used, and since rpi upstream is currently based on 5.10.y, it would be nice to backport the kernel/firmware updates to what is currently the latest stable OE release.

Not sure what is the current update policy for stable branches (if bringing a newer kernel is desirable or not), but I'm opening this pull request so we can discuss what is the preferred way from the upstream perspective.

This pull request is basically master without the gatesgarth incompatible changes, such as the usage of KERNEL_DTC_FLAGS and gstreamer related recipe updates. 

Let me know if the current patch set makes sense for gatesgarth, and if keeping it aligned with the latest master changes is something that is desirable or not.

### CODE REVIEW

**Comment by agherzan** [comment]
@ricardosalveti thanks raising this PR. It is actually the process we are working with. Did everything apply cleanly (for the included commits)?

**Comment by agherzan** [comment]
@agherzan-ci ok to test

**Comment by ricardosalveti** [comment]
> @ricardosalveti thanks for raising this PR. It is actually the process we are working with. Did everything apply cleanly (for the included commits)?

Yes, only had minor conflicts for the kernel update recipes (KERNEL_DTC_FLAGS usage), but it was easy to fix.

**Comment by agherzan** [comment]
Looks good. Merged.

**Pull request merged**
