### PR TITLE
u-boot-rpi: Locate local patches with FILSEXTRAPATHS.

### PR DESCRIPTION
**Pull request by drewmoseley**
Signed-off-by: Drew Moseley <drew.moseley@northern.tech>

**- What I did**

Make sure bitbake can find the patch added by https://github.com/agherzan/meta-raspberrypi/pull/660

**- How I did it**

Update FILESEXTRAPATHS variable.

### CODE REVIEW

**Comment by drewmoseley** [comment]
Since https://github.com/agherzan/meta-raspberrypi/pull/660 is only needed for dunfell, this PR is also only needed for dunfell.

**Comment by drewmoseley** [comment]
@nandra ping

**Comment by drewmoseley** [comment]
@nandra the typo has been fixed.

**Comment by agherzan** [comment]
Thanks guys. Merged.

**Pull request merged**
