### PR TITLE
rpi-libcamera-apps: fix Illegal Instruction

### PR DESCRIPTION
**Pull request by vivien**
With armv8-neon being enforced for all ARM based machines, running any libcamera app on raspberrypi (e.g. Raspberry Pi B Rev 2) results in Illegal Instruction.

To fix this, defaults to TARGET_ARCH for non-aarch64 machines.

### CODE REVIEW

**Review by kraj — APPROVED** [review]
lgtm

**Review by agherzan — APPROVED** [review]
Thanks!

**Comment by agherzan** [comment]
Isn't this affecting master/main?

**Comment by agherzan** [comment]
@vivien can you please submit it for master and afterwards cherry pick + MR for mick?

**Comment by vivien** [comment]
> @vivien can you please submit it for master and afterwards cherry pick + MR for mick?

@agherzan I would argue that is the responsibility of the maintainer, not the developer. Also there is a better approach to this fix actually, so I will send a PR against master along with additional changes.

**Comment by kraj** [comment]
> > @vivien can you please submit it for master and afterwards cherry pick + MR for mick?
> 
> @agherzan I would argue that is the responsibility of the maintainer, not the developer. Also there is a better approach to this fix actually, so I will send a PR against master along with additional changes.

Its perhaps everyone's interest to help maintainer's load as much as possible to keep things in good shape and especially when they ask for it. Generally projects workflows route stable fixes via trunk so even if something is observed on a release branch the process is to
validate it on trunk and in some cases it may not be an issue for trunk but that is to be documented in release branch process.

**Comment by agherzan** [comment]
I would enforce what @kraj wrote above. We can discuss that cherry-picking on stable branches is part of maintainership (even though we are a community, so contributions are always helpful). Still, the changes/fixes are generally sent to the main branch first. And that is part of the public contribution flow. Once that lands, it is in the contributor's interest to test and propose a backport. I hope that makes sense, and thank you for your work.

**Comment by vivien** [comment]
If that part of the maintenance has to be handled by the developers as well, that's fine with me, I'll be happy to do that.

**Comment by agherzan** [comment]
Thanks, @vivien.

**Pull request closed without merging**
