### PR TITLE
merge master changes into dunfell

### PR DESCRIPTION
**Pull request by kraj**

### CODE REVIEW

**Comment by agherzan** [comment]
@kraj this will need a rebase.

**Comment by kraj** [comment]
> @kraj this will need a rebase.

actually this is a proper merge from master with one commit reverted which is not required on
dunfell, so you see the history but actually diff is is only two newest commits in master. This should help future merges as we perhaps will get some frequent patches for future.

I could have just cherry-picked two commits. Do you prefer that ?

**Comment by agherzan** [comment]
Uh, I see. I'd definitely prefer cherry-picks.

**Comment by agherzan** [comment]
Thanks @kraj

**Pull request merged**
