### PR TITLE
99-com.rules: Update rules for BCM2711 based hardware

### PR DESCRIPTION
**Pull request by floion**
Update the rules as per
https://github.com/RPi-Distro/raspberrypi-sys-mods/commit/05cfe136f76677a891a0c77dc91d796913607c07

**- What I did**

**- How I did it**

### CODE REVIEW

**Comment by floion** [comment]
So you mean adding 99-com.rules from https://github.com/agherzan/meta-raspberrypi/blob/master/recipes-core/udev/udev-rules-rpi/99-com.rules in https://github.com/agherzan/meta-raspberrypi/blob/master/recipes-core/udev/udev-rules-rpi.bb as SRC_URI and pull it from there?
What about https://github.com/agherzan/meta-raspberrypi/blob/master/recipes-core/udev/udev-rules-rpi/can.rules ? Would this be installed by the same `udev-rules-rpi` recipe?

**Comment by floion** [comment]
@agherzan you were thinking something along the lines of https://github.com/agherzan/meta-raspberrypi/pull/1185 ?

**Comment by agherzan** [comment]
Exactly. That looks better to me. And maybe in the future split that in its recipe with some deps (to maintain compatibility). So that the rpi udev recipe brings only custom ones and pulls in the raspberry-pi-sys-mods. But for now, this is a good step to avoid any surprises.

**Comment by floion** [comment]
Superseded in favor of https://github.com/agherzan/meta-raspberrypi/pull/1185

**Pull request closed without merging**
