### PR TITLE
u-boot: rename to support 2019.10.

### LINKED ISSUE #510: U-boot recipe out of date
The u-boot recipes require version 2019.07, but yocto has updated to 2019.10 - http://git.yoctoproject.org/cgit.cgi/poky/tree/meta/recipes-bsp/u-boot

### PR DESCRIPTION
**Pull request by patrickvacek**
Fixes #510.

### CODE REVIEW

**Comment by agherzan** [comment]
@agherzan-ci ok to test

**Comment by agherzan** [comment]
Merged. Thanks @patrickvacek

**Comment by shr-project** [comment]
@agherzan please create zeus branch before this commit, because 2019.10 is only in oe-core master for Yocto 3.1 and now meta-raspberrypi master is no longer compatible with oe-core zeus Yocto 3.0.

**Comment by agherzan** [comment]
@shr-project good shout. Pushed the zeus branch.

**Comment by shr-project** [comment]
@agherzan thanks for creating the zeus branch, but it looks like it isn't being synced to git.yoctoproject.org:

http://git.yoctoproject.org/cgit/cgit.cgi/meta-raspberrypi/refs/heads

can you please check why?

**Comment by agherzan** [comment]
@shr-project I have fixed it. Sorry for this. It seems like jenkins doesn't pick up new branches on "SCM change".

**Pull request merged**
