### PR TITLE
Add support for Raspberry Pi Camera Module v3 to Kirkstone

### PR DESCRIPTION
**Pull request by Jessseee**
@floion is requesting at [meta-balena](https://github.com/balena-os/balena-raspberrypi/issues/999#issuecomment-1528739563) for the changes of #1158 to be applied to meta-raspberrypi/kirkstone as well.

### CODE REVIEW

**Review by agherzan — APPROVED** [review]
Looks good.

**Comment by Jessseee** [comment]
It seems the build has run into the issue mentioned by @quaresmajose on #1158.

**Comment by quaresmajose** [comment]
The most reasonable thing to do IMO is backporting the [imx708](https://github.com/raspberrypi/linux/pull/5452) on the kernel 5.10 but please note that it build but doesn't work on this kernel so maybe a note will be needed about that.
In this way kernel 5.10 still be usable and the camera could be used on the 5.15.

**Comment by Jessseee** [comment]
Is it necessary for both kernel version 5.10 and 5.15 to be supported on the Kirkstone branch, as 5.10 is also on Holister, Hardknott and Gatesgarth? It appears that the differences between 5.10 and 5.15 seem to be significant enough that maybe they should not be supported at the same time.

**Comment by Jessseee** [comment]
@agherzan what are your thoughts on this?

**Comment by agherzan** [comment]
@quaresmajose That would be just masking an issue. So I'm not sure if I'm on board with that.
@Jessseee The only clean way I see is to keep the change in master and backport the change on kirkstone in a separate layer. And master to drop 5.10.

**Comment by Jessseee** [comment]
I will try to make a separate layer. Closing this PR for now.

**Pull request closed without merging**
