### PR TITLE
change kernel cfg of drm from y to m to fix the pwm issue #1180

### PR DESCRIPTION
**Pull request by bigbearishappy**
**- What I did**
I was trying to fix the startup problem of the LCD driver in yocto.And I find that the kernel config in yocto of drm is different
with raspbianOS.So I change it same with raspbianOS. And it works fine.

Interestingly, I also find that the PWM issue I create in https://github.com/agherzan/meta-raspberrypi/issues/1180 was fixed.

### CODE REVIEW

**Review by kraj — APPROVED** [review]
Lgtm although I wonder if it will affect images booting out of initramfs

**Comment by bigbearishappy** [comment]
> Lgtm although I wonder if it will affect images booting out of initramfs

Oh, it's already test with booting out of initramfs. And it works fine.

**Review by agherzan — CHANGES_REQUESTED** [review]
Interesting. Can you please add your rationale in git log and have a format as per https://meta-raspberrypi.readthedocs.io/en/latest/contributing.html? Thanks.

**Comment by bigbearishappy** [comment]
> Interesting. Can you please add your rationale in git log and have a format as per https://meta-raspberrypi.readthedocs.io/en/latest/contributing.html? Thanks.

Thanks for your guidance. The git log is updated now. Please let me know if there is any further work I need to do.

**Review by agherzan — APPROVED** [review]

**Comment by agherzan** [comment]
@bigbearishappy is this issue specific to the kirkstone branch? Are you able to give it a spin on the master branch too?

**Comment by bigbearishappy** [comment]
> @bigbearishappy is this issue specific to the kirkstone branch? Are you able to give it a spin on the master branch too?

I think it's not a issue specific to kirkstone. I will have a try with master and create a PR if it's needed.

**Comment by agherzan** [comment]
Please do so that we don't miss it as new versions evolve. Thanks.

**Comment by agherzan** [comment]
@bigbearishappy can you please push this to the branches mentioned above as MRs?

**Pull request merged**
