### PR TITLE
Remove upstreamed U-Boot rpi0w defconfig patch

### PR DESCRIPTION
**Pull request by jonathanhaigh-arm**
The patch 0002-rpi_0_w-Add-configs-consistent-with-RpI3.patch has been
applied to the upstream U-Boot repo and is now in the release that
openembedded-core uses so remove it.

[Issue #239]

Signed-off-by: Jonathan Haigh <jonathan.haigh@arm.com>

### CODE REVIEW

**Comment by jonathanhaigh-arm** [comment]
Hi Andrei, thanks for the review.

I think I've updated the commit message to conform to those guidelines. If I haven't can you let me know which bit needs changing please?

Thanks.

**Comment by jonathanhaigh-arm** [comment]
> u-boot: Remove upstreamed U-Boot rpi0w defconfig patch

Okay, thanks, I'll change to that.

> As well, you mention #239 twice.

The guidelines suggest including a URL when referencing issues, and the example is
```
[RPM Ticket #65] -- http://rpm5.org/cvs/tktview?tn=65,5
```
I used
```
[Issue #239] -- https://github.com/agherzan/meta-raspberrypi/issues/239
```
But GitHub renders both `#239` and the URL as #239. Should I just skip the URL?

**Comment by jonathanhaigh-arm** [comment]
Edited the short description. Hopefully is okay now.

**Comment by agherzan** [comment]
ok to test

**Pull request merged**
