### PR TITLE
ad-hoc fixup for the github SRC_URI mess

### PR DESCRIPTION
**Pull request by TheYoctoJester**
**- What I did**

**- How I did it**

### CODE REVIEW

**Comment by TheYoctoJester** [comment]
Admins of what? Essentially it's just the conversion script from poky applied.

**Comment by shr-project** [comment]
Isn't this already covered by https://github.com/agherzan/meta-raspberrypi/pull/935 ?

**Comment by TheYoctoJester** [comment]
#935 is master, this is dunfell.

**Review by kraj — APPROVED** [review]
lgtm

**Comment by texierp** [comment]
@TheYoctoJester you miss SoB (Signed-off-by) at the end of the commit message ;) [0].
Just use `git commit -s --amend` for that.

In any case, #935 is now merged, maybe it's better to cherry-pick ? 

[0] - https://github.com/agherzan/meta-raspberrypi/blob/master/docs/contributing.md#formatting-patches

**Comment by TheYoctoJester** [comment]
@texierp good point. Will do better next time, just needed a real quick fix to make it build friday afternoon, it only came later to me that a PR might be useful.

Need me to SoB it or going with the CP?

**Comment by shr-project** [comment]
> make it build friday afternoon

isn't https://github.com/openembedded/bitbake/commit/c222eddcebe892ae209aea7776cfc1147ac1df6e enough to get it building with dunfell?

**Comment by texierp** [comment]
> Need me to SoB it or going with the CP?

I think we need to check with @agherzan (the maintainer) about this point ;)

**Comment by TheYoctoJester** [comment]
@shr-project didn't seem to do the trick, sadly.

**Comment by agherzan** [comment]
@TheYoctoJester, @texierp has a very good point. A cherry pick would be much better as I'd be able to track missing backports easier. I'll do it tomorrow and ping you when ready.

**Review by agherzan — CHANGES_REQUESTED** [review]
I'd rather cherry pick master.

**Comment by kraj** [comment]
> I'd rather cherry pick master.

yeah thats better, somehow I thought it was a cherry-pick + mods for dunfell.

**Comment by TheYoctoJester** [comment]
I'm perfectly fine with cherry picking master too :)

**Pull request closed without merging**
