### PR TITLE
machines: Use tune files from renamed location in core

### PR DESCRIPTION
**Pull request by kraj**
Signed-off-by: Khem Raj <raj.khem@gmail.com>

### CODE REVIEW

**Comment by kraj** [comment]
Please hold on merging this until [1] is merged into OE-core

[1] https://lists.openembedded.org/g/openembedded-core/topic/patch_v2_0_3_tunes_the/84935312?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,84935312

**Comment by kraj** [comment]
Please merge this now since relevant OE-core commit is not in master.

**Review by texierp — APPROVED** [review]

**Comment by agherzan** [comment]
@kraj did you mean to hold off merging while OE still lands the needed changes?

**Comment by texierp** [comment]
@agherzan I think It's a typo (not -> now) because the commit is now in OE-Core [1] ;)
You can merge this PR since that the build fails now.

Also, to make your CI happy, you need to install the following packages: lz4c pzstd zstd (see [2] and [3])

[1] - http://cgit.openembedded.org/openembedded-core/commit/?id=b6f15209bcfff953cce69da97a93f9ddff141ced
[2] - https://yocto-ci.resin.io/job/meta-raspberrypi-generic/3482/console
[3] - http://cgit.openembedded.org/openembedded-core/commit/?id=58f5389e3c6b0e5b29df8850c2056b5fc41b618f

**Comment by leon-anavi** [comment]
Hi,

I see the change has landed in Poky branch master so probably it makes sense now to merge this valuable fix in meta-raspberrypi: https://git.yoctoproject.org/cgit.cgi/poky/commit/?id=1d381f21f5f13aa0c4e1a45683ed656ebeedd37d

Thanks,
Leon

**Comment by texierp** [comment]
@leon-anavi yes indeed ;)

**Comment by agherzan** [comment]
Aha! Ok. Let me retrigger CI.

**Review by agherzan — APPROVED** [review]

**Comment by kraj** [comment]
> @kraj did you mean to hold off merging while OE still lands the needed changes?

It’s typo :) please merge this change was what I meant

**Comment by agherzan** [comment]
@kraj  there seems to be a parse error on raspberrypi MACHINE:

**Comment by kraj** [comment]
> @kraj there seems to be a parse error on raspberrypi MACHINE:
> 
> ```
> ERROR: ParseError at /var/lib/jenkins/workspace/meta-raspberrypi-generic/poky/../meta-raspberrypi/conf/machine/raspberrypi.conf:7: Could not include required file conf/machine/include/arm/tune-arm1176jzf-s.inc
> ```

yeah over edited this one file. Fixed now

**Review by texierp — APPROVED** [review]

**Review by agherzan — APPROVED** [review]
Thanks @kraj

**Pull request merged**
