### PR TITLE
recipes: Switch to using UNPACKDIR instead of WORKDIR

### PR DESCRIPTION
**Pull request by kraj**
UNPACKDIR is new contruct for do_unpack things in latest master we should be using that instead of WORKDIR for referencing those files

### CODE REVIEW

**Comment by kraj** [comment]
Please note that this change would not work on scarthgap so we need to branch scarthgap before applying this patch

**Comment by shr-project** [comment]
You might have missed one: https://github.com/agherzan/meta-raspberrypi/pull/1329

**Review by agherzan — APPROVED** [review]
Looks good! Thanks.

**Comment by agherzan** [comment]
Note that I've also created "scarthgap".

**Pull request merged**
