### PR TITLE
gstreamer1.0-plugins-base: Adjust for meson conversion

### PR DESCRIPTION
**Pull request by kraj**
OE-core now uses meson to build gstreamer

Signed-off-by: Khem Raj <raj.khem@gmail.com>

### CODE REVIEW

**Comment by shr-project** [comment]
I've few more changes for this, but my approach depends on oe-core change:
http://git.openembedded.org/openembedded-core-contrib/commit/?h=jansa/master&id=87b5664ed6163ad1259268699a96ee3bf694bc4a
https://github.com/agherzan/meta-raspberrypi/compare/master...shr-project:jansa/gstreamer-vc4?expand=1

**Comment by kraj** [comment]
currently, master is broken ( buildwise ) I would be best to divide your changes such that it can fix the current build without depending on oe-core changes which are still pending. Then we can obsolete this patch. Otherwise lets merge this patch and then you can rebase your changes on top.

**Comment by shr-project** [comment]
Yes, go with your patch and I'll rebase mine after the oe-core part is merged.

**Comment by shr-project** [comment]
> Seems to fail:
> Parsing recipes...ERROR: ParseError at /var/lib/jenkins/workspace/meta-raspberrypi-generic/poky/../meta-openembedded/meta-python/recipes-extended/python-pyparted/python-pyparted_3.11.3.bb:3: Could not inherit file classes/distutils.bbclass

You need to apply all the pending patches for python2-less meta-oe (https://github.com/YoeDistro/meta-openembedded/commits/yoe/mut will let you at least parse).

Khem's gstreamer1.0-omx fixes the build for other MACHINEs, but for rpi it will need more changes, e.g. EXTRA_OECONF_append_rpi  = " CFLAGS="$CFLAGS.. isn't respected anymore, because meson doesn't use EXTRA_OECONF:

| ../gst-omx-1.16.1/omx/gstomx.h:58:10: fatal error: OMX_Broadcom.h: No such file or directory
|    58 | #include <OMX_Broadcom.h>
|       |          ^~~~~~~~~~~~~~~~

adding it directly to CFLAGS variable helps a bit, but then the build fails elsewhere:

../gst-omx-1.16.1/omx/openmax/OMX_VideoExt.h:44:14: error: nested redefinition of 'enum OMX_NALUFORMATSTYPE'
   44 | typedef enum OMX_NALUFORMATSTYPE {
      |              ^~~~~~~~~~~~~~~~~~~

I'll check a bit more why omx got broken during meson transition.

**Comment by agherzan** [comment]
@shr-project Any ETA for getting those upstreamed?

**Comment by shr-project** [comment]
> Any ETA for getting those upstreamed?

It won't be soon, because it still doesn't build (with or without my changes), but khem's commit at least allows to build gstreamer1.0-omx for other MACHINEs (as the PACKAGECONFIG is applied for all MACHINEs not just rpi), so his change should be applied ASAP and then I'll rebase mine when it's ready (and builds correctly for rpi as well).

**Comment by agherzan** [comment]
Merged Martin's PR https://github.com/agherzan/meta-raspberrypi/pull/569 .

**Pull request closed without merging**
