### PR TITLE
sync dunfell with master branch

### PR DESCRIPTION
**Pull request by kraj**
Refresh patches

Signed-off-by: Khem Raj <raj.khem@gmail.com>

### CODE REVIEW

**Comment by kraj** [comment]
I think there is a small issue with missing egl.pc and glesv2.pc files. I will soon send a v2 once fixed.

**Comment by agherzan** [comment]
Should we drop it now that I have merged https://github.com/agherzan/meta-raspberrypi/pull/609 ?

**Comment by kraj** [comment]
this is for dunfell that pull was for master

**Comment by agherzan** [comment]
Hm... where is the dunfell poky branch?

**Comment by kraj** [comment]
It will be created soon

**Comment by kraj** [comment]
dunfell is branched but I plan to refresh this pull request so hold on it.

**Comment by agherzan** [comment]
Gotcha.

**Comment by kraj** [comment]
This merged all changes but 1 from master into dunfell branch. Please take a look

**Pull request merged**
