### PR TITLE
sdcard_image-rpi: replace IMAGE_DEPENDS_rpi-sdimg by do_image_rpi-sdi…

### PR DESCRIPTION
**Pull request by schnitzeltony**
…mg[depends]

* oe-core removed IMAGE_DEPENDS -> parsing fails with hint how to fix
* add required task for each recipe

Signed-off-by: Andreas Müller <schnitzeltony@googlemail.com>

**- What I did**

**- How I did it**

### CODE REVIEW

**Comment by agherzan** [comment]
add to whitelist

**Comment by agherzan** [comment]
ok to test

**Comment by schnitzeltony** [comment]
Strange - as soon as I come over gcc7 fallout I take further care..

**Comment by schnitzeltony** [comment]
s:do_image_rpi-sdimg:do_image_rpi_sdimg - have forced another push - sorry for improper testing

**Comment by agherzan** [comment]
That is fine @schnitzeltony . Does poky manipulate the image type characters replacing dashes with underscores? Didn't know that one.

**Comment by schnitzeltony** [comment]
I don't use - so have no idea what causes that. The error message created helped me:

`ERROR: Task (/home/superandy/oe-core/sources/meta-misc/recipes-image/console/console-base-image-no-nm.bb:do_image_rpi_sdimg) failed with exit code '1'`

**Comment by agherzan** [comment]
Yup. I was wondering why is that the case. Anyway - looks good now.

**Pull request merged**
