### PR TITLE
lirc_%.bbappend: Fix for gpio-ir

### PR DESCRIPTION
**Pull request by leon-anavi**
Apply Raspberry Pi specific fix for gpio-ir kernel module:
https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=235256

Signed-off-by: Leon Anavi <leon.anavi@konsulko.com>

**- What I did**

Fix LIRC on Raspberry Pi with a patch that is known to work with gpio-ir kernel module as explained in the Raspberry Pi forums:
https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=235256

**- How I did it**

With a `.bbappend` file for LIRC that applies the Raspberry Pi specific patch.

Best regards,
Leon

### CODE REVIEW

**Comment by leon-anavi** [comment]
Hi @agherzan,

Thank you for the quick feedback. I've added more details to the git commit message as well as @neuralassembly in "Co-authored-by:" git trailer as he has created the patch and published it in his GitHub repository: https://github.com/neuralassembly/raspi/blob/master/lirc-gpio-ir-0.10.patch

Best regards,
Leon

**Comment by leon-anavi** [comment]
Hi @kraj,

Thank you for the feedback. Following your recommendations I've included a link in the git commit message to [LIRC ticket 359 which is about the upstreaming of this rpi specific patch].(https://sourceforge.net/p/lirc/tickets/359/)

Thanks, Leon

**Comment by agherzan** [comment]
I feel like I'm nitpicking too much on this but I wish we would have had some description in the patch file as well. Including an upstream status.

**Comment by leon-anavi** [comment]
> I feel like I'm nitpicking too much on this but I wish we would have had some description in the patch file as well. Including an upstream status.

Is it OK if I add it as a comment in the recipe rather than in the patch? As stated in the commit message I am not the author of the patch therefore I try avoid changing it directly.

Thanks,
Leon

**Comment by agherzan** [comment]
Right - fair point. Leave like that.

**Comment by leon-anavi** [comment]
Hi @agherzan, @kraj,

Kind reminder regarding the review of this GitHub pull request. Is it OK? Should I change anything else to get it merged?

Thanks,
Leon

**Comment by agherzan** [comment]
Thanks for the kind reminder. Merged.

**Pull request merged**
