### PR TITLE
Clean dunfell and bring master changes

### PR DESCRIPTION
**Pull request by agherzan**
I reverted the custom backports and cleanly added them in the master order so we can maintain the changes easier. Also, one specific change was reverted without backporting because it was broken (https://github.com/agherzan/meta-raspberrypi/pull/660 CC @nandra). This PR misses a `FILESEXTRAPATHS` so please re-push.

This also fixes https://github.com/agherzan/meta-raspberrypi/issues/696.

The only additional fix is `sdcard_image-rpi.bbclass: Fix when RPI_SDIMG_EXTRA_DEPENDS not defined`. That fix is also pushed against `master` (https://github.com/agherzan/meta-raspberrypi/pull/698).

### CODE REVIEW

**Comment by mirzak** [comment]
What is the reason of reverting https://github.com/agherzan/meta-raspberrypi/pull/699/commits/775481dae292df6d17f81790e67307f312534216. Reason I ask is that it is a build breaker, when it was introduce it broke some of our builds and now it will break again if you revert it :)

**Comment by agherzan** [comment]
@mirzak It actually adds it afterwards. This is because by doing it in the same order we avoid conflicts (in this case on `rpi-config_git.bb`) with other commits. The initial backport was not a clean cherry-pick.

**Comment by shr-project** [comment]
LGTM and thanks for fixing that u-boot build.

**Comment by agherzan** [comment]
Thanks for the reviews. Merged.

**Pull request merged**
