### PR TITLE
Backports from master in langdale to fix CI and builds

### PR DESCRIPTION
**Pull request by agherzan**
This includes https://github.com/agherzan/meta-raspberrypi/pull/1107 in `langdale` and other build fixes/backports.

### CODE REVIEW

**Comment by shr-project** [comment]
LGTM. Maybe you can just merge master into langdale as they will be identical after this PR (just with different SHAs if not merged as FF).

**Comment by agherzan** [comment]
Absolutely @shr-project. Done.

**Comment by shr-project** [comment]
Well the fast-forward didn't happen in the end (93dadf3 force-pushed here was correct, but then it was merged as 6f5771d), maybe the repo on github isn't configured to do fast-forward when possible?

```
martin@jama /OE/layers/meta-raspberrypi $ git diff origin/langdale origin/master
martin@jama /OE/layers/meta-raspberrypi $ git log --oneline origin/master..origin/langdale
6f5771d (HEAD -> origin/langdale) raspberrypi4-64: drop DEFAULTTUNE assignment
2d4b292 ci: Fix dco-check job with newer git versions
f581683 ci: Bump actions/checkout to v3
9a5e649 libcamera: rename bbappend to match any version
```

but that's OK.

**Comment by agherzan** [comment]
@shr-project yeah, that is a limitation of GitHub.It doesn't support fast-forward. Which is just annoying,

**Comment by shr-project** [comment]
@agherzan fast-forward works for me, but maybe you don't have "Allow rebase merging" enabled for PRs.

**Pull request merged**
