### PR TITLE
Add recipes for most of the Adafruit CircuitPython Python libraries

### PR DESCRIPTION
**Pull request by mostthingsweb**
This makes it easy to use various Adafruit products, such as the DC & Stepper Motor Bonnet.

### CODE REVIEW

**Review by agherzan — APPROVED** [review]
Looks good to me.

**Comment by agherzan** [comment]
@agherzan-ci ok to test

**Comment by kraj** [comment]
Please fix them for non-rpi machine builds I am seeing 

```
ERROR: Nothing RPROVIDES 'rpi-gpio' (but /home/jenkins/oe/world/yoe/sources/meta-raspberrypi/recipes-devtools/python/python3-adafruit-blinka_6.2.2.bb RDEPENDS on or otherwise requires it)
rpi-gpio was skipped: incompatible with machine qemuarm (not in COMPATIBLE_MACHINE)
NOTE: Runtime target 'rpi-gpio' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rpi-gpio']
NOTE: Runtime target 'python3-adafruit-blinka' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-adafruit-blinka', 'rpi-gpio']
NOTE: Runtime target 'python3-adafruit-circuitpython-busdevice' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-adafruit-circuitpython-busdevice', 'python3-adafruit-blinka', 'rpi-gpio']
NOTE: Runtime target 'python3-adafruit-circuitpython-busdevice-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-adafruit-circuitpython-busdevice-dev', 'python3-adafruit-blinka', 'rpi-gpio']
NOTE: Runtime target 'python3-adafruit-blinka-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-adafruit-blinka-dev', 'rpi-gpio']
NOTE: Multiple providers are available for runtime ssh (dropbear, openssh)
Consider defining a PREFERRED_RPROVIDER entry to match ssh
ERROR: Nothing RPROVIDES 'python3-adafruit-circuitpython-motor' (but /home/jenkins/oe/world/yoe/sources/meta-raspberrypi/recipes-devtools/python/python3-adafruit-circuitpython-motor_3.2.6.bb, /home/jenkins/oe/world/yoe/sources/meta-raspberrypi/recipes-devtools/python/python3-adafruit-circuitpython-motorkit_1.6.1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'python3-adafruit-circuitpython-motor'
NOTE: Runtime target 'python3-adafruit-circuitpython-motor' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-adafruit-circuitpython-motor']
ERROR: Nothing RPROVIDES 'python3-adafruit-circuitpython-motor-dev' (but /home/jenkins/oe/world/yoe/sources/meta-raspberrypi/recipes-devtools/python/python3-adafruit-circuitpython-motor_3.2.6.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'python3-adafruit-circuitpython-motor-dev'
NOTE: Runtime target 'python3-adafruit-circuitpython-motor-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-adafruit-circuitpython-motor-dev']
ERROR: Nothing RPROVIDES 'python3-adafruit-circuitpython-motorkit' (but /home/jenkins/oe/world/yoe/sources/meta-raspberrypi/recipes-devtools/python/python3-adafruit-circuitpython-motorkit_1.6.1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'python3-adafruit-circuitpython-motorkit'
NOTE: Runtime target 'python3-adafruit-circuitpython-motorkit' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-adafruit-circuitpython-motorkit']
ERROR: Nothing RPROVIDES 'python3-adafruit-circuitpython-pca9685' (but /home/jenkins/oe/world/yoe/sources/meta-raspberrypi/recipes-devtools/python/python3-adafruit-circuitpython-motorkit_1.6.1.bb, /home/jenkins/oe/world/yoe/sources/meta-raspberrypi/recipes-devtools/python/python3-adafruit-circuitpython-pca9685_3.3.4.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'python3-adafruit-circuitpython-pca9685'
NOTE: Runtime target 'python3-adafruit-circuitpython-pca9685' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-adafruit-circuitpython-pca9685']
ERROR: Nothing RPROVIDES 'python3-adafruit-circuitpython-motorkit-dev' (but /home/jenkins/oe/world/yoe/sources/meta-raspberrypi/recipes-devtools/python/python3-adafruit-circuitpython-motorkit_1.6.1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'python3-adafruit-circuitpython-motorkit-dev'
NOTE: Runtime target 'python3-adafruit-circuitpython-motorkit-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-adafruit-circuitpython-motorkit-dev']
ERROR: Nothing RPROVIDES 'python3-adafruit-circuitpython-pca9685-dev' (but /home/jenkins/oe/world/yoe/sources/meta-raspberrypi/recipes-devtools/python/python3-adafruit-circuitpython-pca9685_3.3.4.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'python3-adafruit-circuitpython-pca9685-dev'
NOTE: Runtime target 'python3-adafruit-circuitpython-pca9685-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-adafruit-circuitpython-pca9685-dev']
```

building for MACHINE = "qemuarm"

**Comment by kraj** [comment]
@agherzan we should add a qemux86 or qemuarm builds to CI as well.

**Comment by mostthingsweb** [comment]
What build command did you use?

Thanks,
Chris

**Comment by kraj** [comment]
```
MACHINE=qemuarm bitbake world 
```

**Comment by agherzan** [comment]
See the follow-up PRs @mostthingsweb.

**Comment by mostthingsweb** [comment]
@kraj @agherzan thank you for the fixup, sorry I haven't been in front of a computer this weekend.

**Pull request merged**
