### PR TITLE
Updates

### LINKED ISSUE #148: hciattach times out sometimes on first boot for rpi0w
**Description**
I'm using this layer with yocto to build an image for the rpi0-w, and when I first boot the image on the device sometimes it works flawlessly but other times it doesn't set up the bluetooth properly. If it doesn't work on the first boot then rebooting will usually fix it eventually, sometimes running hciattach manually fixes the problem as well. When I dig through the logs I find that the hciattach has timed out during boot. 

**Steps to reproduce the issue:**
1. `bitbake rpi-hwup-image`
2. `dd` image onto sd card
3. boot

**Describe the results you received:**
Sometimes Bluetooth isn't working. There are no devices under `hcitool dev` or `hciconfig`. Also `rfkill` doesn't list the bluetooth device.

**Describe the results you expected:**
For bluetooth to setup the first time.

**Additional information you deem important (e.g. issue happens only occasionally):**
here is the output of `systemctl status brcm43438`:
```
Active: [[0;1;31mfailed[[0m (Result: exit-code) since Mon 2017-10-30 18:21:54 UTC; 28s ago
Process: 162 ExecStart=/usr/bin/hciattach -n /dev/ttyAMA0 bcm43xx 921600 noflow -[[0;1;31m(code=exited, status=1/FAILURE)[[0m
Main PID: 162 (code=exited, status=1/FAILURE)

systemd[1]: Started Broadcom BCM43438 bluetooth HCI.
hciattach[162]: Initialization timed out.
hciattach[162]: bcm43xx_init
systemd[1]: [[0;1;39mbrcm43438.service: Main process exited, code=exited, status=1/FAILURE[[0m
systemd[1]: [[0;1;39mbrcm43438.service: Unit entered failed state.[[0m
systemd[1]: [[0;1;39mbrcm43438.service: Failed with result `exit-code`.[[0m
```
**Additional details (revisions used, host distro, etc.):**
`local.conf`
```PACKAGE_CLASSES ?= "package_rpm"
BB_DISKMON_DIRS = "\
    STOPTASKS,${TMPDIR},1G,100K \
    STOPTASKS,${DL_DIR},1G,100K \
    STOPTASKS,${SSTATE_DIR},1G,100K \
    STOPTASKS,/tmp,100M,100K \
    ABORT,${TMPDIR},100M,1K \
    ABORT,${DL_DIR},100M,1K \
    ABORT,${SSTATE_DIR},100M,1K \
    ABORT,/tmp,10M,1K"
CONF_VERSION = "1"
CORE_IMAGE_EXTRA_INSTALL += "openssh rsync sensorhub"
IMAGE_INSTALL_append += "nodejs nodejs-npm bluez5 networkmanager linux-firmware-bcm43430 config systemd"
IMAGE_INSTALL_append += " crda i2c-tools hostapd linux-firmware-bcm43430 linux-firmware-ralink linux-firmware-rtl8192ce linux-firmware-rtl8192cu linux-firmware-rtl8192su wireless-tools dhcp-client iw wpa-supplicant"
DISTRO_FEATURES_append += " bluez5 bluetooth wifi systemd"```

### LINKED ISSUE #174: hciattach is faulty
**Description**

**Steps to reproduce the issue:**
1. download raspbian image
2. create image using yocto for rpi0w
3. hciattach /dev/ttyAMA0 bcm43xx 3000000 (using the raspian and yocto images)

**Describe the results you received:**
with yocto image, there is initialization timeout. But with the raspbian image, it works fine. I copied the hciattach + the driver to the yocto image (manuall) and it worked. 

**Describe the results you expected:**
hciconfig -a should give a reply that the chip exist

**Additional information you deem important (e.g. issue happens only occasionally):**

**Additional details (revisions used, host distro, etc.):**

### PR DESCRIPTION
**Pull request by agherzan**
**- What I did**

Update linux 4.9 and bluetooth firmware.
Fixes #148

### CODE REVIEW

**Comment by agherzan** [comment]
@sherifomran do you have any information of the firmware version included here? It is the one you sent me. @keeslinp are you able to give this fix a go?

**Comment by sherifomran** [comment]
@agherzan : i don't know the version, but it is from the latest release from raspbian.

**Comment by keeslinp** [comment]
@agherzan It seems like that fixed the bluetooth problem! I haven't tested super extensively but the first try it worked. Unfortunately switching to master from rocko makes my `wlan0` interface disappear :/. I'll look into that and if I can't figure it out I'll make an issue.

**Comment by agherzan** [comment]
That is great. Thanks @keeslinp

**Comment by sherifomran** [comment]
I want to report that i investigated it extensively over 3 days, with many testing methods and baud rates, even that i tested many drivers, some from intell and others. The one i sent out works with 3Gbps fine.

**Comment by keeslinp** [comment]
@agherzan: Since I was able to get the wifi working, I was able to test this out more, now I'm having a weird situation where all my devices have the same mac address when using the master branch. All of my devices now have `43:43:A1:12:1F:AC`. Is it possible that this is a bluez bug? I've tried this on three different devices so far.

**Comment by agherzan** [comment]
That is indeed odd. The mac address should start with `B8:27:EB`. I just checked on a rpi3 of mine (which is based on rocko) and seems to have a sane one.

**Pull request merged**
