### PR TITLE
Add overlays for justboom and reorder

### PR DESCRIPTION
**Pull request by shawaj**
Add overlays for justboom audio boards and reorder list to be in alphabetical order

Change-type: patch
Signed-off-by: Aaron Shaw <aaron@balena.io>

### CODE REVIEW

**Review by kraj — COMMENTED** [review]
usually adding and reordering should be two different patches

**Comment by shawaj** [comment]
@kraj fair enough. So just split into 2 different commits? But keeping on a single PR is ok?

**Comment by kraj** [comment]
> @kraj fair enough. So just split into 2 different commits? But keeping on a single PR is ok?

yes absolutely.

**Comment by shawaj** [comment]
@kraj fixed now :-)

**Review by kraj — APPROVED** [review]
lgtm

**Review by kraj — APPROVED** [review]
lgtm

**Comment by shawaj** [comment]
@kraj does the CI need to test build? How do I / we trigger that?

**Comment by kraj** [comment]
> @kraj does the CI need to test build? How do I / we trigger that?

it should start on pull  request refresh or push

**Comment by shawaj** [comment]
@kraj it doesn't seem to have worked since my last updates?

**Comment by shawaj** [comment]
@agherzan-ci ok to test

**Comment by agherzan** [comment]
@agherzan-ci ok to test

**Review by agherzan — APPROVED** [review]

**Pull request merged**
