### PR TITLE
support for bcm2711-rpi-cm4s

### PR DESCRIPTION
**Pull request by jsebrd**
`recipes-bsp/common`, `recipes-kernel/linux`, `conf/machine/raspberrypi-64.conf`, `conf/machine/include/rpi-base.inc`

Added support for `bcm2711-rpi-cm4s.dtb`.

- update kernel to --> `5.10.92`, `650082a`
- update firmware to --> `20220120`, `c6d5656`

**Reference**
- https://github.com/raspberrypi/linux/pull/4761

Signed-off-by: Jesse Beard <jesse.beard@captiveaire.com>

### CODE REVIEW

**Comment by agherzan** [comment]
This looks reasonably fine excepting for the git log format. Please take a look at https://meta-raspberrypi.readthedocs.io/en/latest/contributing.html#formatting-patches

**Comment by jsebrd** [comment]
@agherzan What do you require to merge this?  Are you unhappy with the PR text or something else?

**Comment by agherzan** [comment]
The PR misses some stuff. But I want those to be checked now with the CI. So I'm postponing the merge for a couple of days until the CI changes get in.
For example, you miss SoB, I would split the kernel and firmware update to the dtb inclusion (3 commits), I would like to keep the namespace subject format etc. Generally, a `git log` would give you examples of how `git log` is expected and also the contribution documentation should provide details and examples. Have you seen it?

**Comment by agherzan** [comment]
> I have adjusted the git log for the commit.  Lmk if you want the commit split into (3) vs. the single commit and I will do so once you confirm.

That would be great. One for firmware bump, one for kernel bump and one for the dtb inclusion. Check `git log` on existing files to check examples of commit logs. We could actually drop the kernel update altogether as there is a pending update for 5.15 which will most probably get in before this.

**Review by agherzan — CHANGES_REQUESTED** [review]
Split into per component commits and drop kernel update. 5.15 update is on the way.

**Review by agherzan — CHANGES_REQUESTED** [review]
A set of issues with this PR:
1. SoB was missing the colon
2. SoB was not matching the author
3. Kernel version was already updated

I will cherry-pick, address these and push as a separate PR keeping SoB for the initial author.

**Comment by agherzan** [comment]
Closing in the favour of: https://github.com/agherzan/meta-raspberrypi/pull/1023

**Comment by agherzan** [comment]
@jsebrd I've looked a bit more into this and it looks that the dtb is only available for arm and not arm64. I see you included it for arm64 along with all the other machines. Was that by mistake?

**Comment by jsebrd** [comment]
@agherzan I will review the commits again and update here.  I integrated the dtb in the way I thought was correct based on my research.  We can work on another PR together to get this properly merged.

**Comment by jsebrd** [comment]
@agherzan So I reviewed the PR and commits I did previously and now much better understand what is happening and where I went wrong the first time.  I no longer require a fork.  Because you have updated the included kernel to 5.15.x line which includes the `.dts` source I need, all I needed to do was create:

```
/recipes-bsp/bootfiles/rpi-bootfiles.bbappend

RPIFW_DATE = "20220308"
SRC_URI[sha256sum] = "5b088e6b39d0054b863c5e9746a8623297e3c8cd98a2ab284a200f54344842da"
```

The firmware checksum was calculated against the binary as:

```
sha256sum raspberrypi-firmware_1.20220308.orig.tar.xz
```

And in my `local.conf` (can also place in distro .conf) ...

```
RPI_KERNEL_DEVICETREE:raspberrypi4 = "bcm2711-rpi-cm4s.dtb"
```

This provides exactly what I need for my specific purposes and eliminates all other non-supported Pi variations and a much leaner `/boot`.

Last thing, as the `/boot/config.txt` requires `otg_mode=1` for proper USB support when we are using the `cm4s`, I am going to examine creating:

```
/recipes-bsp/bootfiles/rpi-config_git.bbappend
```

...to automate the process of adding to the `/boot/config.txt`.

I am working against `meta-raspberrypi/master` until you create an official `kirkstone` branch which I will do as well when you do.

This approach works like a champ for me, but if any of this seems janky, please let me know.

**Pull request closed without merging**
