### PR TITLE
Various updates along with some mailing list patches

### PR DESCRIPTION
**Pull request by agherzan**
* various updates
* pull in patches from the mailing list
* use the rpi test image for CI build validation
* drop deprecated images

### CODE REVIEW

**Review by kraj — DISMISSED** [review]
removing image recipes is good, also check if there is any doc change thats needed.

**Comment by agherzan** [comment]
@kraj Yup, I've dropped the deprecated image references from the docs too.

**Review by zyga — APPROVED** [review]
Looks all-right!

**Review by kraj — APPROVED** [review]
LGTM

**Pull request merged**
