### PR TITLE
Revert "mesa: querying dma_buf modifiers for specific formats"

### PR DESCRIPTION
**Pull request by xyklex**
This reverts commit 84cb8538cd22586fc82daba38458909cedfec2db.

Fixes:
    - https://gitlab.gnome.org/GNOME/mutter/-/issues/1421
    - #711

### CODE REVIEW

**Review by kraj — APPROVED** [review]
lgtm

**Comment by agherzan** [comment]
Where is the rationale behind this revert?

**Comment by xyklex** [comment]
Hi @agherzan, here is the issue of the issue that was happening #711 

I can also confirm that I am able to run mutter and gnome-shell after removing the mesa patch.

**Comment by kraj** [comment]
> Where is the rationale behind this revert?

it is causing regression in running mutter and someone else also reported a different app failing due to this.

**Comment by agherzan** [comment]
I like clean reverts but I'd also include this rationale in the git log this time. @xyklex would you be able to do that? Looks good otherwise. Caught up with the threads in the meanwhile.

**Comment by xyklex** [comment]
@agherzan let me know if I missed something.

**Review by agherzan — APPROVED** [review]
All good merged.

**Pull request merged**
