### PR TITLE
rpidistro-vlc: fix error uint64_t does not name

### PR DESCRIPTION
**Pull request by EasyIP2023**
Build failure occurring with gcc version 13.1.1.

**- What I did**

Add patch to fix builds with latest gcc in OE-core.

**- How I did it**

### CODE REVIEW

**Review by kraj — CHANGES_REQUESTED** [review]
Please backport https://github.com/videolan/vlc/commit/6fca76ebd76bf8fce9b111e31bda64015cdc770f

instead

**Comment by EasyIP2023** [comment]
Hey, @kraj @agherzan Switched patches and ran simple test. Still able to see video through VLC mmal_vout plugin and without an active display server.

**Review by kraj — APPROVED** [review]
lgtm

**Review by agherzan — APPROVED** [review]
Looks good. Thanks.

**Pull request merged**
