### PR TITLE
linux-raspberrypi: upgrade to 6.6.51

### PR DESCRIPTION
**Pull request by moto-timo**
https://github.com/raspberrypi/linux/compare/769634f344626ed73bcda14c91b567067974d7b2..2b5de12af9bb390239d5f3385c49e0c34f335de8

Also update yocto-kernel-cache to 6.6.52

**- What I did**

**- How I did it**

### CODE REVIEW

**Review by kraj — APPROVED** [review]
LGTM

**Comment by agherzan** [comment]
It looks like this doesn't compile.

**Comment by agherzan** [comment]
Builds fail with missing dtbs.

**Comment by agherzan** [comment]
Superseded by https://github.com/agherzan/meta-raspberrypi/pull/1392

**Pull request closed without merging**
